/*-------------------------------------------------------
 * This file was generated by JParser
 *
 * Do not make changes to this file
 *-------------------------------------------------------*/
package bullet;

import com.github.xpenatan.jParser.idl.IDLEnum;

public enum AnisotropicFrictionFlags implements IDLEnum<AnisotropicFrictionFlags> {

    CUSTOM(0), CF_ANISOTROPIC_FRICTION_DISABLED(CF_ANISOTROPIC_FRICTION_DISABLED_NATIVE()), CF_ANISOTROPIC_FRICTION(CF_ANISOTROPIC_FRICTION_NATIVE()), CF_ANISOTROPIC_ROLLING_FRICTION(CF_ANISOTROPIC_ROLLING_FRICTION_NATIVE());

    private int value;

    private AnisotropicFrictionFlags(int value) {
        this.value = value;
    }

    public int getValue() {
        return value;
    }

    public AnisotropicFrictionFlags setValue(int value) {
        if (this != CUSTOM) {
            throw new RuntimeException("Cannot change none CUSTOM value");
        }
        this.value = value;
        return this;
    }

    public AnisotropicFrictionFlags getCustom() {
        return CUSTOM;
    }

    /*[-JNI;-NATIVE]
return (jlong)btCollisionObject::CF_ANISOTROPIC_FRICTION_DISABLED;
*/
    private static native int CF_ANISOTROPIC_FRICTION_DISABLED_NATIVE();

    /*[-JNI;-NATIVE]
return (jlong)btCollisionObject::CF_ANISOTROPIC_FRICTION;
*/
    private static native int CF_ANISOTROPIC_FRICTION_NATIVE();

    /*[-JNI;-NATIVE]
return (jlong)btCollisionObject::CF_ANISOTROPIC_ROLLING_FRICTION;
*/
    private static native int CF_ANISOTROPIC_ROLLING_FRICTION_NATIVE();
}
