/*-------------------------------------------------------
 * This file was generated by JParser
 *
 * Do not make changes to this file
 *-------------------------------------------------------*/
package bullet;

import com.github.xpenatan.jParser.idl.IDLBase;

public class btBroadphasePairArray extends IDLBase {

    private btBroadphasePair btBroadphasePair_TEMP_GEN_0;

    static public final btBroadphasePairArray NULL = btBroadphasePairArray.native_new();

    /**
     * Dummy constructor, used internally to creates objects without C++ pointer
     */
    @Deprecated()
    protected btBroadphasePairArray(byte b, char c) {
    }

    /**
     * @return An empty instance without a native address
     */
    public static btBroadphasePairArray native_new() {
        return new btBroadphasePairArray((byte) 0, (char) 0);
    }

    protected void deleteNative() {
        internal_native_deleteNative(native_address);
    }

    /*[-JNI;-NATIVE]
btBroadphasePairArray* nativeObject = (btBroadphasePairArray*)this_addr;
delete nativeObject;
*/
    public static native void internal_native_deleteNative(long this_addr);

    public int size() {
        return internal_native_size(native_address);
    }

    /*[-JNI;-NATIVE]
btBroadphasePairArray* nativeObject = (btBroadphasePairArray*)this_addr;
return nativeObject->size();
*/
    public static native int internal_native_size(long this_addr);

    public btBroadphasePair at(int n) {
        long pointer = internal_native_at(native_address, n);
        if (pointer == 0)
            return btBroadphasePair.NULL;
        if (btBroadphasePair_TEMP_GEN_0 == null)
            btBroadphasePair_TEMP_GEN_0 = btBroadphasePair.native_new();
        btBroadphasePair_TEMP_GEN_0.internal_reset(pointer, false);
        return btBroadphasePair_TEMP_GEN_0;
    }

    /*[-JNI;-NATIVE]
btBroadphasePairArray* nativeObject = (btBroadphasePairArray*)this_addr;
return (jlong)&nativeObject->at((int)n);
*/
    public static native long internal_native_at(long this_addr, int n);

    public void resize(int value) {
        internal_native_resize(native_address, value);
    }

    /*[-JNI;-NATIVE]
btBroadphasePairArray* nativeObject = (btBroadphasePairArray*)this_addr;
nativeObject->resize((int)value);
*/
    public static native void internal_native_resize(long this_addr, int value);

    public int capacity() {
        return internal_native_capacity(native_address);
    }

    /*[-JNI;-NATIVE]
btBroadphasePairArray* nativeObject = (btBroadphasePairArray*)this_addr;
return nativeObject->capacity();
*/
    public static native int internal_native_capacity(long this_addr);
}
