/*-------------------------------------------------------
 * This file was generated by JParser
 *
 * Do not make changes to this file
 *-------------------------------------------------------*/
package bullet;

import com.github.xpenatan.jParser.idl.IDLBase;
import bullet.bulletcollision.collisiondispatch.btCollisionObject;

public class btConstCollisionObjectArray extends IDLBase {

    private btCollisionObject btCollisionObject_TEMP_GEN_0;

    static public final btConstCollisionObjectArray NULL = btConstCollisionObjectArray.native_new();

    public btConstCollisionObjectArray() {
        long addr = internal_native_create();
        internal_reset(addr, true);
    }

    /*[-JNI;-NATIVE]
return (jlong)new btConstCollisionObjectArray();
*/
    public static native long internal_native_create();

    /**
     * Dummy constructor, used internally to creates objects without C++ pointer
     */
    @Deprecated()
    protected btConstCollisionObjectArray(byte b, char c) {
    }

    /**
     * @return An empty instance without a native address
     */
    public static btConstCollisionObjectArray native_new() {
        return new btConstCollisionObjectArray((byte) 0, (char) 0);
    }

    protected void deleteNative() {
        internal_native_deleteNative(native_address);
    }

    /*[-JNI;-NATIVE]
btConstCollisionObjectArray* nativeObject = (btConstCollisionObjectArray*)this_addr;
delete nativeObject;
*/
    public static native void internal_native_deleteNative(long this_addr);

    public int size() {
        return internal_native_size(native_address);
    }

    /*[-JNI;-NATIVE]
btConstCollisionObjectArray* nativeObject = (btConstCollisionObjectArray*)this_addr;
return nativeObject->size();
*/
    public static native int internal_native_size(long this_addr);

    public btCollisionObject at(int n) {
        long pointer = internal_native_at(native_address, n);
        if (pointer == 0)
            return btCollisionObject.NULL;
        if (btCollisionObject_TEMP_GEN_0 == null)
            btCollisionObject_TEMP_GEN_0 = btCollisionObject.native_new();
        btCollisionObject_TEMP_GEN_0.internal_reset(pointer, false);
        return btCollisionObject_TEMP_GEN_0;
    }

    /*[-JNI;-NATIVE]
btConstCollisionObjectArray* nativeObject = (btConstCollisionObjectArray*)this_addr;
const btCollisionObject* obj = nativeObject->at((int)n);
return (jlong)obj;
*/
    public static native long internal_native_at(long this_addr, int n);

    public void resize(int value) {
        internal_native_resize(native_address, value);
    }

    /*[-JNI;-NATIVE]
btConstCollisionObjectArray* nativeObject = (btConstCollisionObjectArray*)this_addr;
nativeObject->resize((int)value);
*/
    public static native void internal_native_resize(long this_addr, int value);

    public int capacity() {
        return internal_native_capacity(native_address);
    }

    /*[-JNI;-NATIVE]
btConstCollisionObjectArray* nativeObject = (btConstCollisionObjectArray*)this_addr;
return nativeObject->capacity();
*/
    public static native int internal_native_capacity(long this_addr);
}
