/*-------------------------------------------------------
 * This file was generated by JParser
 *
 * Do not make changes to this file
 *-------------------------------------------------------*/
package bullet;

import bullet.bulletcollision.collisionshapes.btCylinderShape;
import bullet.linearmath.btVector3;

public class btCylinderShapeX extends btCylinderShape {

    static public final btCylinderShapeX NULL = btCylinderShapeX.native_new();

    public btCylinderShapeX(btVector3 halfExtents) {
        super((byte) 1, (char) 1);
        long addr = internal_native_create_btVector3(halfExtents.native_address);
        internal_reset(addr, true);
    }

    /*[-JNI;-NATIVE]
return (jlong)new btCylinderShapeX(*((btVector3* )halfExtents_addr));
*/
    public static native long internal_native_create_btVector3(long halfExtents_addr);

    /**
     * Dummy constructor, used internally to creates objects without C++ pointer
     */
    @Deprecated()
    protected btCylinderShapeX(byte b, char c) {
        super((byte) 1, (char) 1);
    }

    /**
     * @return An empty instance without a native address
     */
    public static btCylinderShapeX native_new() {
        return new btCylinderShapeX((byte) 0, (char) 0);
    }

    protected void deleteNative() {
        internal_native_deleteNative(native_address);
    }

    /*[-JNI;-NATIVE]
btCylinderShapeX* nativeObject = (btCylinderShapeX*)this_addr;
delete nativeObject;
*/
    public static native void internal_native_deleteNative(long this_addr);

    public void setMargin(float margin) {
        internal_native_setMargin(native_address, margin);
    }

    /*[-JNI;-NATIVE]
btCylinderShapeX* nativeObject = (btCylinderShapeX*)this_addr;
nativeObject->setMargin((float)margin);
*/
    public static native void internal_native_setMargin(long this_addr, float margin);

    public float getMargin() {
        return internal_native_getMargin(native_address);
    }

    /*[-JNI;-NATIVE]
btCylinderShapeX* nativeObject = (btCylinderShapeX*)this_addr;
return nativeObject->getMargin();
*/
    public static native float internal_native_getMargin(long this_addr);
}
