/*-------------------------------------------------------
 * This file was generated by JParser
 *
 * Do not make changes to this file
 *-------------------------------------------------------*/
package bullet;

import bullet.bulletdynamics.vehicle.btVehicleRaycaster;
import bullet.bulletdynamics.dynamics.btDynamicsWorld;

public class btDefaultVehicleRaycaster extends btVehicleRaycaster {

    static public final btDefaultVehicleRaycaster NULL = btDefaultVehicleRaycaster.native_new();

    public btDefaultVehicleRaycaster(btDynamicsWorld world) {
        super((byte) 1, (char) 1);
        long addr = internal_native_create_btDynamicsWorld(world.native_address);
        internal_reset(addr, true);
    }

    /*[-JNI;-NATIVE]
return (jlong)new btDefaultVehicleRaycaster((btDynamicsWorld* )world_addr);
*/
    public static native long internal_native_create_btDynamicsWorld(long world_addr);

    /**
     * Dummy constructor, used internally to creates objects without C++ pointer
     */
    @Deprecated()
    protected btDefaultVehicleRaycaster(byte b, char c) {
        super((byte) 1, (char) 1);
    }

    /**
     * @return An empty instance without a native address
     */
    public static btDefaultVehicleRaycaster native_new() {
        return new btDefaultVehicleRaycaster((byte) 0, (char) 0);
    }

    protected void deleteNative() {
        internal_native_deleteNative(native_address);
    }

    /*[-JNI;-NATIVE]
btDefaultVehicleRaycaster* nativeObject = (btDefaultVehicleRaycaster*)this_addr;
delete nativeObject;
*/
    public static native void internal_native_deleteNative(long this_addr);
}
