/*-------------------------------------------------------
 * This file was generated by JParser
 *
 * Do not make changes to this file
 *-------------------------------------------------------*/
package bullet;

import com.github.xpenatan.jParser.idl.IDLBase;

public class btDefaultCollisionConstructionInfo extends IDLBase {

    static public final btDefaultCollisionConstructionInfo NULL = btDefaultCollisionConstructionInfo.native_new();

    public btDefaultCollisionConstructionInfo() {
        long addr = internal_native_create();
        internal_reset(addr, true);
    }

    /*[-JNI;-NATIVE]
return (jlong)new btDefaultCollisionConstructionInfo();
*/
    public static native long internal_native_create();

    /**
     * Dummy constructor, used internally to creates objects without C++ pointer
     */
    @Deprecated()
    protected btDefaultCollisionConstructionInfo(byte b, char c) {
    }

    /**
     * @return An empty instance without a native address
     */
    public static btDefaultCollisionConstructionInfo native_new() {
        return new btDefaultCollisionConstructionInfo((byte) 0, (char) 0);
    }

    protected void deleteNative() {
        internal_native_deleteNative(native_address);
    }

    /*[-JNI;-NATIVE]
btDefaultCollisionConstructionInfo* nativeObject = (btDefaultCollisionConstructionInfo*)this_addr;
delete nativeObject;
*/
    public static native void internal_native_deleteNative(long this_addr);
}
