/*-------------------------------------------------------
 * This file was generated by JParser
 *
 * Do not make changes to this file
 *-------------------------------------------------------*/
package bullet;

import com.github.xpenatan.jParser.idl.IDLBase;

public class btGhostPairCallback extends IDLBase {

    static public final btGhostPairCallback NULL = btGhostPairCallback.native_new();

    public btGhostPairCallback() {
        long addr = internal_native_create();
        internal_reset(addr, true);
    }

    /*[-JNI;-NATIVE]
return (jlong)new btGhostPairCallback();
*/
    public static native long internal_native_create();

    /**
     * Dummy constructor, used internally to creates objects without C++ pointer
     */
    @Deprecated()
    protected btGhostPairCallback(byte b, char c) {
    }

    /**
     * @return An empty instance without a native address
     */
    public static btGhostPairCallback native_new() {
        return new btGhostPairCallback((byte) 0, (char) 0);
    }

    protected void deleteNative() {
        internal_native_deleteNative(native_address);
    }

    /*[-JNI;-NATIVE]
btGhostPairCallback* nativeObject = (btGhostPairCallback*)this_addr;
delete nativeObject;
*/
    public static native void internal_native_deleteNative(long this_addr);
}
