/*-------------------------------------------------------
 * This file was generated by JParser
 *
 * Do not make changes to this file
 *-------------------------------------------------------*/
package bullet;

import com.github.xpenatan.jParser.idl.IDLBase;

public class btIndexedMesh extends IDLBase {

    static public final btIndexedMesh NULL = btIndexedMesh.native_new();

    public btIndexedMesh() {
        long addr = internal_native_create();
        internal_reset(addr, true);
    }

    /*[-JNI;-NATIVE]
return (jlong)new btIndexedMesh();
*/
    public static native long internal_native_create();

    /**
     * Dummy constructor, used internally to creates objects without C++ pointer
     */
    @Deprecated()
    protected btIndexedMesh(byte b, char c) {
    }

    /**
     * @return An empty instance without a native address
     */
    public static btIndexedMesh native_new() {
        return new btIndexedMesh((byte) 0, (char) 0);
    }

    protected void deleteNative() {
        internal_native_deleteNative(native_address);
    }

    /*[-JNI;-NATIVE]
btIndexedMesh* nativeObject = (btIndexedMesh*)this_addr;
delete nativeObject;
*/
    public static native void internal_native_deleteNative(long this_addr);
}
