/*-------------------------------------------------------
 * This file was generated by JParser
 *
 * Do not make changes to this file
 *-------------------------------------------------------*/
package bullet;

import bullet.bulletcollision.collisiondispatch.btGhostObject;

public class btPairCachingGhostObject extends btGhostObject {

    static public final btPairCachingGhostObject NULL = btPairCachingGhostObject.native_new();

    public btPairCachingGhostObject() {
        super((byte) 1, (char) 1);
        long addr = internal_native_create();
        internal_reset(addr, true);
    }

    /*[-JNI;-NATIVE]
return (jlong)new btPairCachingGhostObject();
*/
    public static native long internal_native_create();

    /**
     * Dummy constructor, used internally to creates objects without C++ pointer
     */
    @Deprecated()
    protected btPairCachingGhostObject(byte b, char c) {
        super((byte) 1, (char) 1);
    }

    /**
     * @return An empty instance without a native address
     */
    public static btPairCachingGhostObject native_new() {
        return new btPairCachingGhostObject((byte) 0, (char) 0);
    }

    protected void deleteNative() {
        internal_native_deleteNative(native_address);
    }

    /*[-JNI;-NATIVE]
btPairCachingGhostObject* nativeObject = (btPairCachingGhostObject*)this_addr;
delete nativeObject;
*/
    public static native void internal_native_deleteNative(long this_addr);
}
