/*-------------------------------------------------------
 * This file was generated by JParser
 *
 * Do not make changes to this file
 *-------------------------------------------------------*/
package bullet;

import com.github.xpenatan.jParser.idl.IDLBase;
import bullet.bulletsoftbody.btSoftBody;

public class btSoftBodyArray extends IDLBase {

    private btSoftBody btSoftBody_TEMP_GEN_0;

    static public final btSoftBodyArray NULL = btSoftBodyArray.native_new();

    /**
     * Dummy constructor, used internally to creates objects without C++ pointer
     */
    @Deprecated()
    protected btSoftBodyArray(byte b, char c) {
    }

    /**
     * @return An empty instance without a native address
     */
    public static btSoftBodyArray native_new() {
        return new btSoftBodyArray((byte) 0, (char) 0);
    }

    protected void deleteNative() {
        internal_native_deleteNative(native_address);
    }

    /*[-JNI;-NATIVE]
btSoftBodyArray* nativeObject = (btSoftBodyArray*)this_addr;
delete nativeObject;
*/
    public static native void internal_native_deleteNative(long this_addr);

    public int size() {
        return internal_native_size(native_address);
    }

    /*[-JNI;-NATIVE]
btSoftBodyArray* nativeObject = (btSoftBodyArray*)this_addr;
return nativeObject->size();
*/
    public static native int internal_native_size(long this_addr);

    public btSoftBody at(int n) {
        long pointer = internal_native_at(native_address, n);
        if (pointer == 0)
            return btSoftBody.NULL;
        if (btSoftBody_TEMP_GEN_0 == null)
            btSoftBody_TEMP_GEN_0 = btSoftBody.native_new();
        btSoftBody_TEMP_GEN_0.internal_reset(pointer, false);
        return btSoftBody_TEMP_GEN_0;
    }

    /*[-JNI;-NATIVE]
btSoftBodyArray* nativeObject = (btSoftBodyArray*)this_addr;
const btSoftBody* obj = nativeObject->at((int)n);
return (jlong)obj;
*/
    public static native long internal_native_at(long this_addr, int n);
}
