/*-------------------------------------------------------
 * This file was generated by JParser
 *
 * Do not make changes to this file
 *-------------------------------------------------------*/
package bullet;

import com.github.xpenatan.jParser.idl.IDLBase;

public class btSoftBodySolver extends IDLBase {

    static public final btSoftBodySolver NULL = btSoftBodySolver.native_new();

    /**
     * Dummy constructor, used internally to creates objects without C++ pointer
     */
    @Deprecated()
    protected btSoftBodySolver(byte b, char c) {
    }

    /**
     * @return An empty instance without a native address
     */
    public static btSoftBodySolver native_new() {
        return new btSoftBodySolver((byte) 0, (char) 0);
    }

    protected void deleteNative() {
        internal_native_deleteNative(native_address);
    }

    /*[-JNI;-NATIVE]
btSoftBodySolver* nativeObject = (btSoftBodySolver*)this_addr;
delete nativeObject;
*/
    public static native void internal_native_deleteNative(long this_addr);
}
