/*-------------------------------------------------------
 * This file was generated by JParser
 *
 * Do not make changes to this file
 *-------------------------------------------------------*/
package bullet;

import com.github.xpenatan.jParser.idl.IDLBase;
import bullet.linearmath.btVector3;

public class btVector3Array extends IDLBase {

    private btVector3 btVector3_TEMP_GEN_0;

    static public final btVector3Array NULL = btVector3Array.native_new();

    public btVector3Array() {
        long addr = internal_native_create();
        internal_reset(addr, true);
    }

    /*[-JNI;-NATIVE]
return (jlong)new btVector3Array();
*/
    public static native long internal_native_create();

    /**
     * Dummy constructor, used internally to creates objects without C++ pointer
     */
    @Deprecated()
    protected btVector3Array(byte b, char c) {
    }

    /**
     * @return An empty instance without a native address
     */
    public static btVector3Array native_new() {
        return new btVector3Array((byte) 0, (char) 0);
    }

    protected void deleteNative() {
        internal_native_deleteNative(native_address);
    }

    /*[-JNI;-NATIVE]
btVector3Array* nativeObject = (btVector3Array*)this_addr;
delete nativeObject;
*/
    public static native void internal_native_deleteNative(long this_addr);

    public int size() {
        return internal_native_size(native_address);
    }

    /*[-JNI;-NATIVE]
btVector3Array* nativeObject = (btVector3Array*)this_addr;
return nativeObject->size();
*/
    public static native int internal_native_size(long this_addr);

    public btVector3 at(int n) {
        long pointer = internal_native_at(native_address, n);
        if (pointer == 0)
            return btVector3.NULL;
        if (btVector3_TEMP_GEN_0 == null)
            btVector3_TEMP_GEN_0 = btVector3.native_new();
        btVector3_TEMP_GEN_0.internal_reset(pointer, false);
        return btVector3_TEMP_GEN_0;
    }

    /*[-JNI;-NATIVE]
btVector3Array* nativeObject = (btVector3Array*)this_addr;
static btVector3 copy_addr;
copy_addr = nativeObject->at((int)n);
return (jlong)&copy_addr;*/
    public static native long internal_native_at(long this_addr, int n);

    public void resize(int value) {
        internal_native_resize(native_address, value);
    }

    /*[-JNI;-NATIVE]
btVector3Array* nativeObject = (btVector3Array*)this_addr;
nativeObject->resize((int)value);
*/
    public static native void internal_native_resize(long this_addr, int value);

    public int capacity() {
        return internal_native_capacity(native_address);
    }

    /*[-JNI;-NATIVE]
btVector3Array* nativeObject = (btVector3Array*)this_addr;
return nativeObject->capacity();
*/
    public static native int internal_native_capacity(long this_addr);
}
