/*
  -------------------------------------------------------
   This file was generated by JParser
 
   Do not make changes to this file
  -------------------------------------------------------
*/
package bullet;

import com.github.xpenatan.jparser.loader.JParserLibraryLoader;
import com.github.xpenatan.jparser.loader.JParserLibraryLoaderListener;

/**
 * @author xpenatan
 */
public class BulletLoader {

    /*
      [-JNI;-NATIVE]
             #include "BulletCustom.h"
    */
    public static void init(JParserLibraryLoaderListener listener) {
        JParserLibraryLoader.load("bullet", listener);
    }

    /**
     * Not compatible with the web
     */
    public static void initSync(JParserLibraryLoaderListener listener) {
        JParserLibraryLoader.loadSync("bullet", listener);
    }
}
