/*-------------------------------------------------------
 * This file was generated by JParser
 *
 * Do not make changes to this file
 *-------------------------------------------------------*/
package bullet;

import bullet.linearmath.btVector3;

public class ClosestConvexResultCallback extends ConvexResultCallback {

    private btVector3 btVector3_TEMP_GEN_0;

    private btVector3 btVector3_TEMP_GEN_1;

    private btVector3 btVector3_TEMP_GEN_2;

    private btVector3 btVector3_TEMP_GEN_3;

    static public final ClosestConvexResultCallback NULL = ClosestConvexResultCallback.native_new();

    public ClosestConvexResultCallback(btVector3 convexFromWorld, btVector3 convexToWorld) {
        super((byte) 1, (char) 1);
        long addr = internal_native_create_btVector3_btVector3(convexFromWorld.native_address, convexToWorld.native_address);
        internal_reset(addr, true);
    }

    /*[-JNI;-NATIVE]
return (jlong)new btCollisionWorld::ClosestConvexResultCallback(*((btVector3* )convexFromWorld_addr), *((btVector3* )convexToWorld_addr));
*/
    public static native long internal_native_create_btVector3_btVector3(long convexFromWorld_addr, long convexToWorld_addr);

    /**
     * Dummy constructor, used internally to creates objects without C++ pointer
     */
    @Deprecated()
    protected ClosestConvexResultCallback(byte b, char c) {
        super((byte) 1, (char) 1);
    }

    /**
     * @return An empty instance without a native address
     */
    public static ClosestConvexResultCallback native_new() {
        return new ClosestConvexResultCallback((byte) 0, (char) 0);
    }

    protected void deleteNative() {
        internal_native_deleteNative(native_address);
    }

    /*[-JNI;-NATIVE]
btCollisionWorld::ClosestConvexResultCallback* nativeObject = (btCollisionWorld::ClosestConvexResultCallback*)this_addr;
delete nativeObject;
*/
    public static native void internal_native_deleteNative(long this_addr);

    public btVector3 get_m_convexFromWorld() {
        long pointer = internal_native_get_m_convexFromWorld(native_address);
        if (pointer == 0)
            return btVector3.NULL;
        if (btVector3_TEMP_GEN_0 == null)
            btVector3_TEMP_GEN_0 = btVector3.native_new();
        btVector3_TEMP_GEN_0.internal_reset(pointer, false);
        return btVector3_TEMP_GEN_0;
    }

    /*[-JNI;-NATIVE]
btCollisionWorld::ClosestConvexResultCallback* nativeObject = (btCollisionWorld::ClosestConvexResultCallback*)this_addr;
return (jlong)&nativeObject->m_convexFromWorld;
*/
    public static native long internal_native_get_m_convexFromWorld(long this_addr);

    public void set_m_convexFromWorld(btVector3 m_convexFromWorld) {
        internal_native_set_m_convexFromWorld(native_address, m_convexFromWorld.native_address);
    }

    /*[-JNI;-NATIVE]
btCollisionWorld::ClosestConvexResultCallback* nativeObject = (btCollisionWorld::ClosestConvexResultCallback*)this_addr;
nativeObject->m_convexFromWorld = *((btVector3*)m_convexFromWorld_addr);
*/
    public static native void internal_native_set_m_convexFromWorld(long this_addr, long m_convexFromWorld_addr);

    public btVector3 get_m_convexToWorld() {
        long pointer = internal_native_get_m_convexToWorld(native_address);
        if (pointer == 0)
            return btVector3.NULL;
        if (btVector3_TEMP_GEN_1 == null)
            btVector3_TEMP_GEN_1 = btVector3.native_new();
        btVector3_TEMP_GEN_1.internal_reset(pointer, false);
        return btVector3_TEMP_GEN_1;
    }

    /*[-JNI;-NATIVE]
btCollisionWorld::ClosestConvexResultCallback* nativeObject = (btCollisionWorld::ClosestConvexResultCallback*)this_addr;
return (jlong)&nativeObject->m_convexToWorld;
*/
    public static native long internal_native_get_m_convexToWorld(long this_addr);

    public void set_m_convexToWorld(btVector3 m_convexToWorld) {
        internal_native_set_m_convexToWorld(native_address, m_convexToWorld.native_address);
    }

    /*[-JNI;-NATIVE]
btCollisionWorld::ClosestConvexResultCallback* nativeObject = (btCollisionWorld::ClosestConvexResultCallback*)this_addr;
nativeObject->m_convexToWorld = *((btVector3*)m_convexToWorld_addr);
*/
    public static native void internal_native_set_m_convexToWorld(long this_addr, long m_convexToWorld_addr);

    public btVector3 get_m_hitNormalWorld() {
        long pointer = internal_native_get_m_hitNormalWorld(native_address);
        if (pointer == 0)
            return btVector3.NULL;
        if (btVector3_TEMP_GEN_2 == null)
            btVector3_TEMP_GEN_2 = btVector3.native_new();
        btVector3_TEMP_GEN_2.internal_reset(pointer, false);
        return btVector3_TEMP_GEN_2;
    }

    /*[-JNI;-NATIVE]
btCollisionWorld::ClosestConvexResultCallback* nativeObject = (btCollisionWorld::ClosestConvexResultCallback*)this_addr;
return (jlong)&nativeObject->m_hitNormalWorld;
*/
    public static native long internal_native_get_m_hitNormalWorld(long this_addr);

    public void set_m_hitNormalWorld(btVector3 m_hitNormalWorld) {
        internal_native_set_m_hitNormalWorld(native_address, m_hitNormalWorld.native_address);
    }

    /*[-JNI;-NATIVE]
btCollisionWorld::ClosestConvexResultCallback* nativeObject = (btCollisionWorld::ClosestConvexResultCallback*)this_addr;
nativeObject->m_hitNormalWorld = *((btVector3*)m_hitNormalWorld_addr);
*/
    public static native void internal_native_set_m_hitNormalWorld(long this_addr, long m_hitNormalWorld_addr);

    public btVector3 get_m_hitPointWorld() {
        long pointer = internal_native_get_m_hitPointWorld(native_address);
        if (pointer == 0)
            return btVector3.NULL;
        if (btVector3_TEMP_GEN_3 == null)
            btVector3_TEMP_GEN_3 = btVector3.native_new();
        btVector3_TEMP_GEN_3.internal_reset(pointer, false);
        return btVector3_TEMP_GEN_3;
    }

    /*[-JNI;-NATIVE]
btCollisionWorld::ClosestConvexResultCallback* nativeObject = (btCollisionWorld::ClosestConvexResultCallback*)this_addr;
return (jlong)&nativeObject->m_hitPointWorld;
*/
    public static native long internal_native_get_m_hitPointWorld(long this_addr);

    public void set_m_hitPointWorld(btVector3 m_hitPointWorld) {
        internal_native_set_m_hitPointWorld(native_address, m_hitPointWorld.native_address);
    }

    /*[-JNI;-NATIVE]
btCollisionWorld::ClosestConvexResultCallback* nativeObject = (btCollisionWorld::ClosestConvexResultCallback*)this_addr;
nativeObject->m_hitPointWorld = *((btVector3*)m_hitPointWorld_addr);
*/
    public static native void internal_native_set_m_hitPointWorld(long this_addr, long m_hitPointWorld_addr);
}
