/*-------------------------------------------------------
 * This file was generated by JParser
 *
 * Do not make changes to this file
 *-------------------------------------------------------*/
package bullet;

import com.github.xpenatan.jParser.idl.IDLEnum;

public enum CollisionObjectTypes implements IDLEnum<CollisionObjectTypes> {

    CUSTOM(0),
    CO_COLLISION_OBJECT(CO_COLLISION_OBJECT_NATIVE()),
    CO_RIGID_BODY(CO_RIGID_BODY_NATIVE()),
    CO_GHOST_OBJECT(CO_GHOST_OBJECT_NATIVE()),
    CO_SOFT_BODY(CO_SOFT_BODY_NATIVE()),
    CO_HF_FLUID(CO_HF_FLUID_NATIVE()),
    CO_USER_TYPE(CO_USER_TYPE_NATIVE()),
    CO_FEATHERSTONE_LINK(CO_FEATHERSTONE_LINK_NATIVE());

    private int value;

    private CollisionObjectTypes(int value) {
        this.value = value;
    }

    public int getValue() {
        return value;
    }

    public CollisionObjectTypes setValue(int value) {
        if (this != CUSTOM) {
            throw new RuntimeException("Cannot change none CUSTOM value");
        }
        this.value = value;
        return this;
    }

    public CollisionObjectTypes getCustom() {
        return CUSTOM;
    }

    /*[-JNI;-NATIVE]
return (jlong)btCollisionObject::CO_COLLISION_OBJECT;
*/
    private static native int CO_COLLISION_OBJECT_NATIVE();

    /*[-JNI;-NATIVE]
return (jlong)btCollisionObject::CO_RIGID_BODY;
*/
    private static native int CO_RIGID_BODY_NATIVE();

    /*[-JNI;-NATIVE]
return (jlong)btCollisionObject::CO_GHOST_OBJECT;
*/
    private static native int CO_GHOST_OBJECT_NATIVE();

    /*[-JNI;-NATIVE]
return (jlong)btCollisionObject::CO_SOFT_BODY;
*/
    private static native int CO_SOFT_BODY_NATIVE();

    /*[-JNI;-NATIVE]
return (jlong)btCollisionObject::CO_HF_FLUID;
*/
    private static native int CO_HF_FLUID_NATIVE();

    /*[-JNI;-NATIVE]
return (jlong)btCollisionObject::CO_USER_TYPE;
*/
    private static native int CO_USER_TYPE_NATIVE();

    /*[-JNI;-NATIVE]
return (jlong)btCollisionObject::CO_FEATHERSTONE_LINK;
*/
    private static native int CO_FEATHERSTONE_LINK_NATIVE();
}
