/*-------------------------------------------------------
 * This file was generated by JParser
 *
 * Do not make changes to this file
 *-------------------------------------------------------*/
package bullet;

import com.github.xpenatan.jParser.idl.IDLBase;

public class ConvexResultCallback extends IDLBase {

    static public final ConvexResultCallback NULL = ConvexResultCallback.native_new();

    /**
     * Dummy constructor, used internally to creates objects without C++ pointer
     */
    @Deprecated()
    protected ConvexResultCallback(byte b, char c) {
    }

    /**
     * @return An empty instance without a native address
     */
    public static ConvexResultCallback native_new() {
        return new ConvexResultCallback((byte) 0, (char) 0);
    }

    protected void deleteNative() {
        internal_native_deleteNative(native_address);
    }

    /*[-JNI;-NATIVE]
btCollisionWorld::ConvexResultCallback* nativeObject = (btCollisionWorld::ConvexResultCallback*)this_addr;
delete nativeObject;
*/
    public static native void internal_native_deleteNative(long this_addr);

    public boolean hasHit() {
        return internal_native_hasHit(native_address);
    }

    /*[-JNI;-NATIVE]
btCollisionWorld::ConvexResultCallback* nativeObject = (btCollisionWorld::ConvexResultCallback*)this_addr;
return nativeObject->hasHit();
*/
    public static native boolean internal_native_hasHit(long this_addr);

    public int get_m_collisionFilterGroup() {
        return internal_native_get_m_collisionFilterGroup(native_address);
    }

    /*[-JNI;-NATIVE]
btCollisionWorld::ConvexResultCallback* nativeObject = (btCollisionWorld::ConvexResultCallback*)this_addr;
return nativeObject->m_collisionFilterGroup;
*/
    public static native int internal_native_get_m_collisionFilterGroup(long this_addr);

    public void set_m_collisionFilterGroup(int m_collisionFilterGroup) {
        internal_native_set_m_collisionFilterGroup(native_address, m_collisionFilterGroup);
    }

    /*[-JNI;-NATIVE]
btCollisionWorld::ConvexResultCallback* nativeObject = (btCollisionWorld::ConvexResultCallback*)this_addr;
nativeObject->m_collisionFilterGroup = m_collisionFilterGroup;
*/
    public static native void internal_native_set_m_collisionFilterGroup(long this_addr, int m_collisionFilterGroup);

    public int get_m_collisionFilterMask() {
        return internal_native_get_m_collisionFilterMask(native_address);
    }

    /*[-JNI;-NATIVE]
btCollisionWorld::ConvexResultCallback* nativeObject = (btCollisionWorld::ConvexResultCallback*)this_addr;
return nativeObject->m_collisionFilterMask;
*/
    public static native int internal_native_get_m_collisionFilterMask(long this_addr);

    public void set_m_collisionFilterMask(int m_collisionFilterMask) {
        internal_native_set_m_collisionFilterMask(native_address, m_collisionFilterMask);
    }

    /*[-JNI;-NATIVE]
btCollisionWorld::ConvexResultCallback* nativeObject = (btCollisionWorld::ConvexResultCallback*)this_addr;
nativeObject->m_collisionFilterMask = m_collisionFilterMask;
*/
    public static native void internal_native_set_m_collisionFilterMask(long this_addr, int m_collisionFilterMask);

    public float get_m_closestHitFraction() {
        return internal_native_get_m_closestHitFraction(native_address);
    }

    /*[-JNI;-NATIVE]
btCollisionWorld::ConvexResultCallback* nativeObject = (btCollisionWorld::ConvexResultCallback*)this_addr;
return nativeObject->m_closestHitFraction;
*/
    public static native float internal_native_get_m_closestHitFraction(long this_addr);

    public void set_m_closestHitFraction(float m_closestHitFraction) {
        internal_native_set_m_closestHitFraction(native_address, m_closestHitFraction);
    }

    /*[-JNI;-NATIVE]
btCollisionWorld::ConvexResultCallback* nativeObject = (btCollisionWorld::ConvexResultCallback*)this_addr;
nativeObject->m_closestHitFraction = m_closestHitFraction;
*/
    public static native void internal_native_set_m_closestHitFraction(long this_addr, float m_closestHitFraction);
}
