/*-------------------------------------------------------
 * This file was generated by JParser
 *
 * Do not make changes to this file
 *-------------------------------------------------------*/
package bullet;

import com.github.xpenatan.jParser.idl.IDLEnum;

public enum DebugDrawModes implements IDLEnum<DebugDrawModes> {

    CUSTOM(0),
    DBG_NoDebug(DBG_NoDebug_NATIVE()),
    DBG_DrawWireframe(DBG_DrawWireframe_NATIVE()),
    DBG_DrawAabb(DBG_DrawAabb_NATIVE()),
    DBG_DrawFeaturesText(DBG_DrawFeaturesText_NATIVE()),
    DBG_DrawContactPoints(DBG_DrawContactPoints_NATIVE()),
    DBG_NoDeactivation(DBG_NoDeactivation_NATIVE()),
    DBG_NoHelpText(DBG_NoHelpText_NATIVE()),
    DBG_DrawText(DBG_DrawText_NATIVE()),
    DBG_ProfileTimings(DBG_ProfileTimings_NATIVE()),
    DBG_EnableSatComparison(DBG_EnableSatComparison_NATIVE()),
    DBG_DisableBulletLCP(DBG_DisableBulletLCP_NATIVE()),
    DBG_EnableCCD(DBG_EnableCCD_NATIVE()),
    DBG_DrawConstraints(DBG_DrawConstraints_NATIVE()),
    DBG_DrawConstraintLimits(DBG_DrawConstraintLimits_NATIVE()),
    DBG_FastWireframe(DBG_FastWireframe_NATIVE()),
    DBG_DrawNormals(DBG_DrawNormals_NATIVE()),
    DBG_DrawFrames(DBG_DrawFrames_NATIVE()),
    DBG_MAX_DEBUG_DRAW_MODE(DBG_MAX_DEBUG_DRAW_MODE_NATIVE());

    private int value;

    private DebugDrawModes(int value) {
        this.value = value;
    }

    public int getValue() {
        return value;
    }

    public DebugDrawModes setValue(int value) {
        if (this != CUSTOM) {
            throw new RuntimeException("Cannot change none CUSTOM value");
        }
        this.value = value;
        return this;
    }

    public DebugDrawModes getCustom() {
        return CUSTOM;
    }

    /*[-JNI;-NATIVE]
return (jlong)btIDebugDraw::DBG_NoDebug;
*/
    private static native int DBG_NoDebug_NATIVE();

    /*[-JNI;-NATIVE]
return (jlong)btIDebugDraw::DBG_DrawWireframe;
*/
    private static native int DBG_DrawWireframe_NATIVE();

    /*[-JNI;-NATIVE]
return (jlong)btIDebugDraw::DBG_DrawAabb;
*/
    private static native int DBG_DrawAabb_NATIVE();

    /*[-JNI;-NATIVE]
return (jlong)btIDebugDraw::DBG_DrawFeaturesText;
*/
    private static native int DBG_DrawFeaturesText_NATIVE();

    /*[-JNI;-NATIVE]
return (jlong)btIDebugDraw::DBG_DrawContactPoints;
*/
    private static native int DBG_DrawContactPoints_NATIVE();

    /*[-JNI;-NATIVE]
return (jlong)btIDebugDraw::DBG_NoDeactivation;
*/
    private static native int DBG_NoDeactivation_NATIVE();

    /*[-JNI;-NATIVE]
return (jlong)btIDebugDraw::DBG_NoHelpText;
*/
    private static native int DBG_NoHelpText_NATIVE();

    /*[-JNI;-NATIVE]
return (jlong)btIDebugDraw::DBG_DrawText;
*/
    private static native int DBG_DrawText_NATIVE();

    /*[-JNI;-NATIVE]
return (jlong)btIDebugDraw::DBG_ProfileTimings;
*/
    private static native int DBG_ProfileTimings_NATIVE();

    /*[-JNI;-NATIVE]
return (jlong)btIDebugDraw::DBG_EnableSatComparison;
*/
    private static native int DBG_EnableSatComparison_NATIVE();

    /*[-JNI;-NATIVE]
return (jlong)btIDebugDraw::DBG_DisableBulletLCP;
*/
    private static native int DBG_DisableBulletLCP_NATIVE();

    /*[-JNI;-NATIVE]
return (jlong)btIDebugDraw::DBG_EnableCCD;
*/
    private static native int DBG_EnableCCD_NATIVE();

    /*[-JNI;-NATIVE]
return (jlong)btIDebugDraw::DBG_DrawConstraints;
*/
    private static native int DBG_DrawConstraints_NATIVE();

    /*[-JNI;-NATIVE]
return (jlong)btIDebugDraw::DBG_DrawConstraintLimits;
*/
    private static native int DBG_DrawConstraintLimits_NATIVE();

    /*[-JNI;-NATIVE]
return (jlong)btIDebugDraw::DBG_FastWireframe;
*/
    private static native int DBG_FastWireframe_NATIVE();

    /*[-JNI;-NATIVE]
return (jlong)btIDebugDraw::DBG_DrawNormals;
*/
    private static native int DBG_DrawNormals_NATIVE();

    /*[-JNI;-NATIVE]
return (jlong)btIDebugDraw::DBG_DrawFrames;
*/
    private static native int DBG_DrawFrames_NATIVE();

    /*[-JNI;-NATIVE]
return (jlong)btIDebugDraw::DBG_MAX_DEBUG_DRAW_MODE;
*/
    private static native int DBG_MAX_DEBUG_DRAW_MODE_NATIVE();
}
