/*-------------------------------------------------------
 * This file was generated by JParser
 *
 * Do not make changes to this file
 *-------------------------------------------------------*/
package bullet;

import com.github.xpenatan.jParser.idl.IDLBase;

public class LocalShapeInfo extends IDLBase {

    static public final LocalShapeInfo NULL = LocalShapeInfo.native_new();

    /**
     * Dummy constructor, used internally to creates objects without C++ pointer
     */
    @Deprecated()
    protected LocalShapeInfo(byte b, char c) {
    }

    /**
     * @return An empty instance without a native address
     */
    public static LocalShapeInfo native_new() {
        return new LocalShapeInfo((byte) 0, (char) 0);
    }

    protected void deleteNative() {
        internal_native_deleteNative(native_address);
    }

    /*[-JNI;-NATIVE]
btCollisionWorld::LocalShapeInfo* nativeObject = (btCollisionWorld::LocalShapeInfo*)this_addr;
delete nativeObject;
*/
    public static native void internal_native_deleteNative(long this_addr);

    public int get_m_shapePart() {
        return internal_native_get_m_shapePart(native_address);
    }

    /*[-JNI;-NATIVE]
btCollisionWorld::LocalShapeInfo* nativeObject = (btCollisionWorld::LocalShapeInfo*)this_addr;
return nativeObject->m_shapePart;
*/
    public static native int internal_native_get_m_shapePart(long this_addr);

    public void set_m_shapePart(int m_shapePart) {
        internal_native_set_m_shapePart(native_address, m_shapePart);
    }

    /*[-JNI;-NATIVE]
btCollisionWorld::LocalShapeInfo* nativeObject = (btCollisionWorld::LocalShapeInfo*)this_addr;
nativeObject->m_shapePart = m_shapePart;
*/
    public static native void internal_native_set_m_shapePart(long this_addr, int m_shapePart);

    public int get_m_triangleIndex() {
        return internal_native_get_m_triangleIndex(native_address);
    }

    /*[-JNI;-NATIVE]
btCollisionWorld::LocalShapeInfo* nativeObject = (btCollisionWorld::LocalShapeInfo*)this_addr;
return nativeObject->m_triangleIndex;
*/
    public static native int internal_native_get_m_triangleIndex(long this_addr);

    public void set_m_triangleIndex(int m_triangleIndex) {
        internal_native_set_m_triangleIndex(native_address, m_triangleIndex);
    }

    /*[-JNI;-NATIVE]
btCollisionWorld::LocalShapeInfo* nativeObject = (btCollisionWorld::LocalShapeInfo*)this_addr;
nativeObject->m_triangleIndex = m_triangleIndex;
*/
    public static native void internal_native_set_m_triangleIndex(long this_addr, int m_triangleIndex);
}
