/*-------------------------------------------------------
 * This file was generated by JParser
 *
 * Do not make changes to this file
 *-------------------------------------------------------*/
package bullet;

import com.github.xpenatan.jParser.idl.IDLBase;
import bullet.bulletcollision.collisiondispatch.btCollisionObject;
import bullet.linearmath.btVector3;

public class LocalConvexResult extends IDLBase {

    private btCollisionObject btCollisionObject_TEMP_GEN_0;

    private LocalShapeInfo LocalShapeInfo_TEMP_GEN_0;

    private btVector3 btVector3_TEMP_GEN_0;

    private btVector3 btVector3_TEMP_GEN_1;

    static public final LocalConvexResult NULL = LocalConvexResult.native_new();

    public LocalConvexResult(btCollisionObject hitCollisionObject, LocalShapeInfo localShapeInfo, btVector3 hitNormalLocal, btVector3 hitPointLocal, float hitFraction) {
        long addr = internal_native_create_btCollisionObject_LocalShapeInfo_btVector3_btVector3_float(hitCollisionObject.native_address, localShapeInfo.native_address, hitNormalLocal.native_address, hitPointLocal.native_address, hitFraction);
        internal_reset(addr, true);
    }

    /*[-JNI;-NATIVE]
return (jlong)new btCollisionWorld::LocalConvexResult((btCollisionObject* )hitCollisionObject_addr, (btCollisionWorld::LocalShapeInfo* )localShapeInfo_addr, *((btVector3* )hitNormalLocal_addr), *((btVector3* )hitPointLocal_addr), (float)hitFraction);
*/
    public static native long internal_native_create_btCollisionObject_LocalShapeInfo_btVector3_btVector3_float(long hitCollisionObject_addr, long localShapeInfo_addr, long hitNormalLocal_addr, long hitPointLocal_addr, float hitFraction);

    /**
     * Dummy constructor, used internally to creates objects without C++ pointer
     */
    @Deprecated()
    protected LocalConvexResult(byte b, char c) {
    }

    /**
     * @return An empty instance without a native address
     */
    public static LocalConvexResult native_new() {
        return new LocalConvexResult((byte) 0, (char) 0);
    }

    protected void deleteNative() {
        internal_native_deleteNative(native_address);
    }

    /*[-JNI;-NATIVE]
btCollisionWorld::LocalConvexResult* nativeObject = (btCollisionWorld::LocalConvexResult*)this_addr;
delete nativeObject;
*/
    public static native void internal_native_deleteNative(long this_addr);

    public btCollisionObject get_m_hitCollisionObject() {
        long pointer = internal_native_get_m_hitCollisionObject(native_address);
        if (pointer == 0)
            return btCollisionObject.NULL;
        if (btCollisionObject_TEMP_GEN_0 == null)
            btCollisionObject_TEMP_GEN_0 = btCollisionObject.native_new();
        btCollisionObject_TEMP_GEN_0.internal_reset(pointer, false);
        return btCollisionObject_TEMP_GEN_0;
    }

    /*[-JNI;-NATIVE]
btCollisionWorld::LocalConvexResult* nativeObject = (btCollisionWorld::LocalConvexResult*)this_addr;
const btCollisionObject* attr = nativeObject->m_hitCollisionObject;
return (jlong)attr;
*/
    public static native long internal_native_get_m_hitCollisionObject(long this_addr);

    public void set_m_hitCollisionObject(btCollisionObject m_hitCollisionObject) {
        internal_native_set_m_hitCollisionObject(native_address, m_hitCollisionObject.native_address);
    }

    /*[-JNI;-NATIVE]
btCollisionWorld::LocalConvexResult* nativeObject = (btCollisionWorld::LocalConvexResult*)this_addr;
nativeObject->m_hitCollisionObject = (btCollisionObject*)m_hitCollisionObject_addr;
*/
    public static native void internal_native_set_m_hitCollisionObject(long this_addr, long m_hitCollisionObject_addr);

    public LocalShapeInfo get_m_localShapeInfo() {
        long pointer = internal_native_get_m_localShapeInfo(native_address);
        if (pointer == 0)
            return LocalShapeInfo.NULL;
        if (LocalShapeInfo_TEMP_GEN_0 == null)
            LocalShapeInfo_TEMP_GEN_0 = LocalShapeInfo.native_new();
        LocalShapeInfo_TEMP_GEN_0.internal_reset(pointer, false);
        return LocalShapeInfo_TEMP_GEN_0;
    }

    /*[-JNI;-NATIVE]
btCollisionWorld::LocalConvexResult* nativeObject = (btCollisionWorld::LocalConvexResult*)this_addr;
btCollisionWorld::LocalShapeInfo* attr = nativeObject->m_localShapeInfo;
return (jlong)attr;
*/
    public static native long internal_native_get_m_localShapeInfo(long this_addr);

    public void set_m_localShapeInfo(LocalShapeInfo m_localShapeInfo) {
        internal_native_set_m_localShapeInfo(native_address, m_localShapeInfo.native_address);
    }

    /*[-JNI;-NATIVE]
btCollisionWorld::LocalConvexResult* nativeObject = (btCollisionWorld::LocalConvexResult*)this_addr;
nativeObject->m_localShapeInfo = (btCollisionWorld::LocalShapeInfo*)m_localShapeInfo_addr;
*/
    public static native void internal_native_set_m_localShapeInfo(long this_addr, long m_localShapeInfo_addr);

    public btVector3 get_m_hitNormalLocal() {
        long pointer = internal_native_get_m_hitNormalLocal(native_address);
        if (pointer == 0)
            return btVector3.NULL;
        if (btVector3_TEMP_GEN_0 == null)
            btVector3_TEMP_GEN_0 = btVector3.native_new();
        btVector3_TEMP_GEN_0.internal_reset(pointer, false);
        return btVector3_TEMP_GEN_0;
    }

    /*[-JNI;-NATIVE]
btCollisionWorld::LocalConvexResult* nativeObject = (btCollisionWorld::LocalConvexResult*)this_addr;
return (jlong)&nativeObject->m_hitNormalLocal;
*/
    public static native long internal_native_get_m_hitNormalLocal(long this_addr);

    public void set_m_hitNormalLocal(btVector3 m_hitNormalLocal) {
        internal_native_set_m_hitNormalLocal(native_address, m_hitNormalLocal.native_address);
    }

    /*[-JNI;-NATIVE]
btCollisionWorld::LocalConvexResult* nativeObject = (btCollisionWorld::LocalConvexResult*)this_addr;
nativeObject->m_hitNormalLocal = *((btVector3*)m_hitNormalLocal_addr);
*/
    public static native void internal_native_set_m_hitNormalLocal(long this_addr, long m_hitNormalLocal_addr);

    public btVector3 get_m_hitPointLocal() {
        long pointer = internal_native_get_m_hitPointLocal(native_address);
        if (pointer == 0)
            return btVector3.NULL;
        if (btVector3_TEMP_GEN_1 == null)
            btVector3_TEMP_GEN_1 = btVector3.native_new();
        btVector3_TEMP_GEN_1.internal_reset(pointer, false);
        return btVector3_TEMP_GEN_1;
    }

    /*[-JNI;-NATIVE]
btCollisionWorld::LocalConvexResult* nativeObject = (btCollisionWorld::LocalConvexResult*)this_addr;
return (jlong)&nativeObject->m_hitPointLocal;
*/
    public static native long internal_native_get_m_hitPointLocal(long this_addr);

    public void set_m_hitPointLocal(btVector3 m_hitPointLocal) {
        internal_native_set_m_hitPointLocal(native_address, m_hitPointLocal.native_address);
    }

    /*[-JNI;-NATIVE]
btCollisionWorld::LocalConvexResult* nativeObject = (btCollisionWorld::LocalConvexResult*)this_addr;
nativeObject->m_hitPointLocal = *((btVector3*)m_hitPointLocal_addr);
*/
    public static native void internal_native_set_m_hitPointLocal(long this_addr, long m_hitPointLocal_addr);

    public float get_m_hitFraction() {
        return internal_native_get_m_hitFraction(native_address);
    }

    /*[-JNI;-NATIVE]
btCollisionWorld::LocalConvexResult* nativeObject = (btCollisionWorld::LocalConvexResult*)this_addr;
return nativeObject->m_hitFraction;
*/
    public static native float internal_native_get_m_hitFraction(long this_addr);

    public void set_m_hitFraction(float m_hitFraction) {
        internal_native_set_m_hitFraction(native_address, m_hitFraction);
    }

    /*[-JNI;-NATIVE]
btCollisionWorld::LocalConvexResult* nativeObject = (btCollisionWorld::LocalConvexResult*)this_addr;
nativeObject->m_hitFraction = m_hitFraction;
*/
    public static native void internal_native_set_m_hitFraction(long this_addr, float m_hitFraction);
}
