/*-------------------------------------------------------
 * This file was generated by JParser
 *
 * Do not make changes to this file
 *-------------------------------------------------------*/
package bullet;

import com.github.xpenatan.jParser.idl.IDLBase;
import bullet.bulletcollision.collisiondispatch.btCollisionObject;
import bullet.linearmath.btVector3;

public class LocalRayResult extends IDLBase {

    private btCollisionObject btCollisionObject_TEMP_GEN_0;

    private LocalShapeInfo LocalShapeInfo_TEMP_GEN_0;

    private btVector3 btVector3_TEMP_GEN_0;

    static public final LocalRayResult NULL = LocalRayResult.native_new();

    /**
     * Dummy constructor, used internally to creates objects without C++ pointer
     */
    @Deprecated()
    protected LocalRayResult(byte b, char c) {
    }

    /**
     * @return An empty instance without a native address
     */
    public static LocalRayResult native_new() {
        return new LocalRayResult((byte) 0, (char) 0);
    }

    protected void deleteNative() {
        internal_native_deleteNative(native_address);
    }

    /*[-JNI;-NATIVE]
btCollisionWorld::LocalRayResult* nativeObject = (btCollisionWorld::LocalRayResult*)this_addr;
delete nativeObject;
*/
    public static native void internal_native_deleteNative(long this_addr);

    public btCollisionObject get_m_collisionObject() {
        long pointer = internal_native_get_m_collisionObject(native_address);
        if (pointer == 0)
            return btCollisionObject.NULL;
        if (btCollisionObject_TEMP_GEN_0 == null)
            btCollisionObject_TEMP_GEN_0 = btCollisionObject.native_new();
        btCollisionObject_TEMP_GEN_0.internal_reset(pointer, false);
        return btCollisionObject_TEMP_GEN_0;
    }

    /*[-JNI;-NATIVE]
btCollisionWorld::LocalRayResult* nativeObject = (btCollisionWorld::LocalRayResult*)this_addr;
const btCollisionObject* attr = nativeObject->m_collisionObject;
return (jlong)attr;
*/
    public static native long internal_native_get_m_collisionObject(long this_addr);

    public void set_m_collisionObject(btCollisionObject m_collisionObject) {
        internal_native_set_m_collisionObject(native_address, m_collisionObject.native_address);
    }

    /*[-JNI;-NATIVE]
btCollisionWorld::LocalRayResult* nativeObject = (btCollisionWorld::LocalRayResult*)this_addr;
nativeObject->m_collisionObject = (btCollisionObject*)m_collisionObject_addr;
*/
    public static native void internal_native_set_m_collisionObject(long this_addr, long m_collisionObject_addr);

    public LocalShapeInfo get_m_localShapeInfo() {
        long pointer = internal_native_get_m_localShapeInfo(native_address);
        if (pointer == 0)
            return LocalShapeInfo.NULL;
        if (LocalShapeInfo_TEMP_GEN_0 == null)
            LocalShapeInfo_TEMP_GEN_0 = LocalShapeInfo.native_new();
        LocalShapeInfo_TEMP_GEN_0.internal_reset(pointer, false);
        return LocalShapeInfo_TEMP_GEN_0;
    }

    /*[-JNI;-NATIVE]
btCollisionWorld::LocalRayResult* nativeObject = (btCollisionWorld::LocalRayResult*)this_addr;
btCollisionWorld::LocalShapeInfo* attr = nativeObject->m_localShapeInfo;
return (jlong)attr;
*/
    public static native long internal_native_get_m_localShapeInfo(long this_addr);

    public void set_m_localShapeInfo(LocalShapeInfo m_localShapeInfo) {
        internal_native_set_m_localShapeInfo(native_address, m_localShapeInfo.native_address);
    }

    /*[-JNI;-NATIVE]
btCollisionWorld::LocalRayResult* nativeObject = (btCollisionWorld::LocalRayResult*)this_addr;
nativeObject->m_localShapeInfo = (btCollisionWorld::LocalShapeInfo*)m_localShapeInfo_addr;
*/
    public static native void internal_native_set_m_localShapeInfo(long this_addr, long m_localShapeInfo_addr);

    public btVector3 get_m_hitNormalLocal() {
        long pointer = internal_native_get_m_hitNormalLocal(native_address);
        if (pointer == 0)
            return btVector3.NULL;
        if (btVector3_TEMP_GEN_0 == null)
            btVector3_TEMP_GEN_0 = btVector3.native_new();
        btVector3_TEMP_GEN_0.internal_reset(pointer, false);
        return btVector3_TEMP_GEN_0;
    }

    /*[-JNI;-NATIVE]
btCollisionWorld::LocalRayResult* nativeObject = (btCollisionWorld::LocalRayResult*)this_addr;
return (jlong)&nativeObject->m_hitNormalLocal;
*/
    public static native long internal_native_get_m_hitNormalLocal(long this_addr);

    public void set_m_hitNormalLocal(btVector3 m_hitNormalLocal) {
        internal_native_set_m_hitNormalLocal(native_address, m_hitNormalLocal.native_address);
    }

    /*[-JNI;-NATIVE]
btCollisionWorld::LocalRayResult* nativeObject = (btCollisionWorld::LocalRayResult*)this_addr;
nativeObject->m_hitNormalLocal = *((btVector3*)m_hitNormalLocal_addr);
*/
    public static native void internal_native_set_m_hitNormalLocal(long this_addr, long m_hitNormalLocal_addr);

    public float get_m_hitFraction() {
        return internal_native_get_m_hitFraction(native_address);
    }

    /*[-JNI;-NATIVE]
btCollisionWorld::LocalRayResult* nativeObject = (btCollisionWorld::LocalRayResult*)this_addr;
return nativeObject->m_hitFraction;
*/
    public static native float internal_native_get_m_hitFraction(long this_addr);

    public void set_m_hitFraction(float m_hitFraction) {
        internal_native_set_m_hitFraction(native_address, m_hitFraction);
    }

    /*[-JNI;-NATIVE]
btCollisionWorld::LocalRayResult* nativeObject = (btCollisionWorld::LocalRayResult*)this_addr;
nativeObject->m_hitFraction = m_hitFraction;
*/
    public static native void internal_native_set_m_hitFraction(long this_addr, float m_hitFraction);
}
