/*-------------------------------------------------------
 * This file was generated by JParser
 *
 * Do not make changes to this file
 *-------------------------------------------------------*/
package bullet.bulletcollision.broadphasecollision;

import bullet.linearmath.btVector3;

public class btAxisSweep3 extends btBroadphaseInterface {

    static public final btAxisSweep3 NULL = btAxisSweep3.native_new();

    public btAxisSweep3(btVector3 worldAabbMin, btVector3 worldAabbMax, int maxHandles, btOverlappingPairCache pairCache, boolean disableRaycastAccelerator) {
        super((byte) 1, (char) 1);
        long addr = internal_native_create_btVector3_btVector3_int_btOverlappingPairCache_boolean(worldAabbMin.native_address, worldAabbMax.native_address, maxHandles, pairCache.native_address, disableRaycastAccelerator);
        internal_reset(addr, true);
    }

    /*[-JNI;-NATIVE]
return (jlong)new btAxisSweep3(*((btVector3* )worldAabbMin_addr), *((btVector3* )worldAabbMax_addr), (int)maxHandles, (btOverlappingPairCache* )pairCache_addr, disableRaycastAccelerator);
*/
    public static native long internal_native_create_btVector3_btVector3_int_btOverlappingPairCache_boolean(long worldAabbMin_addr, long worldAabbMax_addr, int maxHandles, long pairCache_addr, boolean disableRaycastAccelerator);

    public btAxisSweep3(btVector3 worldAabbMin, btVector3 worldAabbMax, int maxHandles, btOverlappingPairCache pairCache) {
        super((byte) 1, (char) 1);
        long addr = internal_native_create_btVector3_btVector3_int_btOverlappingPairCache(worldAabbMin.native_address, worldAabbMax.native_address, maxHandles, pairCache.native_address);
        internal_reset(addr, true);
    }

    /*[-JNI;-NATIVE]
return (jlong)new btAxisSweep3(*((btVector3* )worldAabbMin_addr), *((btVector3* )worldAabbMax_addr), (int)maxHandles, (btOverlappingPairCache* )pairCache_addr);
*/
    public static native long internal_native_create_btVector3_btVector3_int_btOverlappingPairCache(long worldAabbMin_addr, long worldAabbMax_addr, int maxHandles, long pairCache_addr);

    public btAxisSweep3(btVector3 worldAabbMin, btVector3 worldAabbMax, int maxHandles) {
        super((byte) 1, (char) 1);
        long addr = internal_native_create_btVector3_btVector3_int(worldAabbMin.native_address, worldAabbMax.native_address, maxHandles);
        internal_reset(addr, true);
    }

    /*[-JNI;-NATIVE]
return (jlong)new btAxisSweep3(*((btVector3* )worldAabbMin_addr), *((btVector3* )worldAabbMax_addr), (int)maxHandles);
*/
    public static native long internal_native_create_btVector3_btVector3_int(long worldAabbMin_addr, long worldAabbMax_addr, int maxHandles);

    public btAxisSweep3(btVector3 worldAabbMin, btVector3 worldAabbMax) {
        super((byte) 1, (char) 1);
        long addr = internal_native_create_btVector3_btVector3(worldAabbMin.native_address, worldAabbMax.native_address);
        internal_reset(addr, true);
    }

    /*[-JNI;-NATIVE]
return (jlong)new btAxisSweep3(*((btVector3* )worldAabbMin_addr), *((btVector3* )worldAabbMax_addr));
*/
    public static native long internal_native_create_btVector3_btVector3(long worldAabbMin_addr, long worldAabbMax_addr);

    /**
     * Dummy constructor, used internally to creates objects without C++ pointer
     */
    @Deprecated()
    protected btAxisSweep3(byte b, char c) {
        super((byte) 1, (char) 1);
    }

    /**
     * @return An empty instance without a native address
     */
    public static btAxisSweep3 native_new() {
        return new btAxisSweep3((byte) 0, (char) 0);
    }

    protected void deleteNative() {
        internal_native_deleteNative(native_address);
    }

    /*[-JNI;-NATIVE]
btAxisSweep3* nativeObject = (btAxisSweep3*)this_addr;
delete nativeObject;
*/
    public static native void internal_native_deleteNative(long this_addr);
}
