/*-------------------------------------------------------
 * This file was generated by JParser
 *
 * Do not make changes to this file
 *-------------------------------------------------------*/
package bullet.bulletcollision.broadphasecollision;

import com.github.xpenatan.jParser.idl.IDLBase;

public class btBroadphaseProxy extends IDLBase {

    static public final btBroadphaseProxy NULL = btBroadphaseProxy.native_new();

    /**
     * Dummy constructor, used internally to creates objects without C++ pointer
     */
    @Deprecated()
    protected btBroadphaseProxy(byte b, char c) {
    }

    /**
     * @return An empty instance without a native address
     */
    public static btBroadphaseProxy native_new() {
        return new btBroadphaseProxy((byte) 0, (char) 0);
    }

    protected void deleteNative() {
        internal_native_deleteNative(native_address);
    }

    /*[-JNI;-NATIVE]
btBroadphaseProxy* nativeObject = (btBroadphaseProxy*)this_addr;
delete nativeObject;
*/
    public static native void internal_native_deleteNative(long this_addr);
}
