/*-------------------------------------------------------
 * This file was generated by JParser
 *
 * Do not make changes to this file
 *-------------------------------------------------------*/
package bullet.bulletcollision.broadphasecollision;

import com.github.xpenatan.jParser.idl.IDLBase;

public class btBroadphaseInterface extends IDLBase {

    private btOverlappingPairCache btOverlappingPairCache_TEMP_GEN_0;

    static public final btBroadphaseInterface NULL = btBroadphaseInterface.native_new();

    /**
     * Dummy constructor, used internally to creates objects without C++ pointer
     */
    @Deprecated()
    protected btBroadphaseInterface(byte b, char c) {
    }

    /**
     * @return An empty instance without a native address
     */
    public static btBroadphaseInterface native_new() {
        return new btBroadphaseInterface((byte) 0, (char) 0);
    }

    protected void deleteNative() {
        internal_native_deleteNative(native_address);
    }

    /*[-JNI;-NATIVE]
btBroadphaseInterface* nativeObject = (btBroadphaseInterface*)this_addr;
delete nativeObject;
*/
    public static native void internal_native_deleteNative(long this_addr);

    public btOverlappingPairCache getOverlappingPairCache() {
        long pointer = internal_native_getOverlappingPairCache(native_address);
        if (pointer == 0)
            return btOverlappingPairCache.NULL;
        if (btOverlappingPairCache_TEMP_GEN_0 == null)
            btOverlappingPairCache_TEMP_GEN_0 = btOverlappingPairCache.native_new();
        btOverlappingPairCache_TEMP_GEN_0.internal_reset(pointer, false);
        return btOverlappingPairCache_TEMP_GEN_0;
    }

    /*[-JNI;-NATIVE]
btBroadphaseInterface* nativeObject = (btBroadphaseInterface*)this_addr;
btOverlappingPairCache* obj = nativeObject->getOverlappingPairCache();
return (jlong)obj;
*/
    public static native long internal_native_getOverlappingPairCache(long this_addr);
}
