/*-------------------------------------------------------
 * This file was generated by JParser
 *
 * Do not make changes to this file
 *-------------------------------------------------------*/
package bullet.bulletcollision.broadphasecollision;

import com.github.xpenatan.jParser.idl.IDLBase;
import bullet.btManifoldArray;

public class btCollisionAlgorithm extends IDLBase {

    static public final btCollisionAlgorithm NULL = btCollisionAlgorithm.native_new();

    /**
     * Dummy constructor, used internally to creates objects without C++ pointer
     */
    @Deprecated()
    protected btCollisionAlgorithm(byte b, char c) {
    }

    /**
     * @return An empty instance without a native address
     */
    public static btCollisionAlgorithm native_new() {
        return new btCollisionAlgorithm((byte) 0, (char) 0);
    }

    protected void deleteNative() {
        internal_native_deleteNative(native_address);
    }

    /*[-JNI;-NATIVE]
btCollisionAlgorithm* nativeObject = (btCollisionAlgorithm*)this_addr;
delete nativeObject;
*/
    public static native void internal_native_deleteNative(long this_addr);

    public void getAllContactManifolds(btManifoldArray manifoldArray) {
        internal_native_getAllContactManifolds(native_address, manifoldArray.native_address);
    }

    /*[-JNI;-NATIVE]
btCollisionAlgorithm* nativeObject = (btCollisionAlgorithm*)this_addr;
nativeObject->getAllContactManifolds(*((btManifoldArray* )manifoldArray_addr));
*/
    public static native void internal_native_getAllContactManifolds(long this_addr, long manifoldArray_addr);
}
