/*-------------------------------------------------------
 * This file was generated by JParser
 *
 * Do not make changes to this file
 *-------------------------------------------------------*/
package bullet.bulletcollision.broadphasecollision;

import com.github.xpenatan.jParser.idl.IDLBase;
import bullet.bulletcollision.narrowphasecollision.btPersistentManifold;

public class btDispatcher extends IDLBase {

    private btPersistentManifold btPersistentManifold_TEMP_GEN_0;

    static public final btDispatcher NULL = btDispatcher.native_new();

    /**
     * Dummy constructor, used internally to creates objects without C++ pointer
     */
    @Deprecated()
    protected btDispatcher(byte b, char c) {
    }

    /**
     * @return An empty instance without a native address
     */
    public static btDispatcher native_new() {
        return new btDispatcher((byte) 0, (char) 0);
    }

    protected void deleteNative() {
        internal_native_deleteNative(native_address);
    }

    /*[-JNI;-NATIVE]
btDispatcher* nativeObject = (btDispatcher*)this_addr;
delete nativeObject;
*/
    public static native void internal_native_deleteNative(long this_addr);

    public int getNumManifolds() {
        return internal_native_getNumManifolds(native_address);
    }

    /*[-JNI;-NATIVE]
btDispatcher* nativeObject = (btDispatcher*)this_addr;
return nativeObject->getNumManifolds();
*/
    public static native int internal_native_getNumManifolds(long this_addr);

    public btPersistentManifold getManifoldByIndexInternal(int index) {
        long pointer = internal_native_getManifoldByIndexInternal(native_address, index);
        if (pointer == 0)
            return btPersistentManifold.NULL;
        if (btPersistentManifold_TEMP_GEN_0 == null)
            btPersistentManifold_TEMP_GEN_0 = btPersistentManifold.native_new();
        btPersistentManifold_TEMP_GEN_0.internal_reset(pointer, false);
        return btPersistentManifold_TEMP_GEN_0;
    }

    /*[-JNI;-NATIVE]
btDispatcher* nativeObject = (btDispatcher*)this_addr;
btPersistentManifold* obj = nativeObject->getManifoldByIndexInternal((int)index);
return (jlong)obj;
*/
    public static native long internal_native_getManifoldByIndexInternal(long this_addr, int index);
}
