/*
  -------------------------------------------------------
   This file was generated by JParser
 
   Do not make changes to this file
  -------------------------------------------------------
*/
package bullet.idl.helper;

public class IDLUtils {

    public static String getJSString(long addr) {
        return null;
    }
}
