/*-------------------------------------------------------
 * This file was generated by JParser
 *
 * Do not make changes to this file
 *-------------------------------------------------------*/
package bullet.bulletdynamics.vehicle;

import com.github.xpenatan.jParser.idl.IDLBase;

public class btVehicleRaycaster extends IDLBase {

    static public final btVehicleRaycaster NULL = btVehicleRaycaster.native_new();

    /**
     * Dummy constructor, used internally to creates objects without C++ pointer
     */
    @Deprecated()
    protected btVehicleRaycaster(byte b, char c) {
    }

    /**
     * @return An empty instance without a native address
     */
    public static btVehicleRaycaster native_new() {
        return new btVehicleRaycaster((byte) 0, (char) 0);
    }

    protected void deleteNative() {
        internal_native_deleteNative(native_address);
    }

    /*[-JNI;-NATIVE]
btVehicleRaycaster* nativeObject = (btVehicleRaycaster*)this_addr;
delete nativeObject;
*/
    public static native void internal_native_deleteNative(long this_addr);
}
