/*-------------------------------------------------------
 * This file was generated by JParser
 *
 * Do not make changes to this file
 *-------------------------------------------------------*/
package bullet.linearmath;

import com.github.xpenatan.jParser.idl.IDLBase;

public class btQuadWord extends IDLBase {

    static public final btQuadWord NULL = btQuadWord.native_new();

    /**
     * Dummy constructor, used internally to creates objects without C++ pointer
     */
    @Deprecated()
    protected btQuadWord(byte b, char c) {
    }

    /**
     * @return An empty instance without a native address
     */
    public static btQuadWord native_new() {
        return new btQuadWord((byte) 0, (char) 0);
    }

    protected void deleteNative() {
        internal_native_deleteNative(native_address);
    }

    /*[-JNI;-NATIVE]
btQuadWord* nativeObject = (btQuadWord*)this_addr;
delete nativeObject;
*/
    public static native void internal_native_deleteNative(long this_addr);

    public float getX() {
        return internal_native_getX(native_address);
    }

    /*[-JNI;-NATIVE]
btQuadWord* nativeObject = (btQuadWord*)this_addr;
return nativeObject->getX();
*/
    public static native float internal_native_getX(long this_addr);

    public float getY() {
        return internal_native_getY(native_address);
    }

    /*[-JNI;-NATIVE]
btQuadWord* nativeObject = (btQuadWord*)this_addr;
return nativeObject->getY();
*/
    public static native float internal_native_getY(long this_addr);

    public float getZ() {
        return internal_native_getZ(native_address);
    }

    /*[-JNI;-NATIVE]
btQuadWord* nativeObject = (btQuadWord*)this_addr;
return nativeObject->getZ();
*/
    public static native float internal_native_getZ(long this_addr);

    public void setX(float x) {
        internal_native_setX(native_address, x);
    }

    /*[-JNI;-NATIVE]
btQuadWord* nativeObject = (btQuadWord*)this_addr;
nativeObject->setX((float)x);
*/
    public static native void internal_native_setX(long this_addr, float x);

    public void setY(float y) {
        internal_native_setY(native_address, y);
    }

    /*[-JNI;-NATIVE]
btQuadWord* nativeObject = (btQuadWord*)this_addr;
nativeObject->setY((float)y);
*/
    public static native void internal_native_setY(long this_addr, float y);

    public void setZ(float z) {
        internal_native_setZ(native_address, z);
    }

    /*[-JNI;-NATIVE]
btQuadWord* nativeObject = (btQuadWord*)this_addr;
nativeObject->setZ((float)z);
*/
    public static native void internal_native_setZ(long this_addr, float z);

    public void setW(float w) {
        internal_native_setW(native_address, w);
    }

    /*[-JNI;-NATIVE]
btQuadWord* nativeObject = (btQuadWord*)this_addr;
nativeObject->setW((float)w);
*/
    public static native void internal_native_setW(long this_addr, float w);
}
