/*-------------------------------------------------------
 * This file was generated by JParser
 *
 * Do not make changes to this file
 *-------------------------------------------------------*/
package bullet.bulletsoftbody;

import bullet.bulletcollision.collisiondispatch.btDefaultCollisionConfiguration;
import bullet.btDefaultCollisionConstructionInfo;

public class btSoftBodyRigidBodyCollisionConfiguration extends btDefaultCollisionConfiguration {

    static public final btSoftBodyRigidBodyCollisionConfiguration NULL = btSoftBodyRigidBodyCollisionConfiguration.native_new();

    public btSoftBodyRigidBodyCollisionConfiguration(btDefaultCollisionConstructionInfo info) {
        super((byte) 1, (char) 1);
        long addr = internal_native_create_btDefaultCollisionConstructionInfo(info.native_address);
        internal_reset(addr, true);
    }

    /*[-JNI;-NATIVE]
return (jlong)new btSoftBodyRigidBodyCollisionConfiguration(*((btDefaultCollisionConstructionInfo* )info_addr));
*/
    public static native long internal_native_create_btDefaultCollisionConstructionInfo(long info_addr);

    public btSoftBodyRigidBodyCollisionConfiguration() {
        super((byte) 1, (char) 1);
        long addr = internal_native_create();
        internal_reset(addr, true);
    }

    /*[-JNI;-NATIVE]
return (jlong)new btSoftBodyRigidBodyCollisionConfiguration();
*/
    public static native long internal_native_create();

    /**
     * Dummy constructor, used internally to creates objects without C++ pointer
     */
    @Deprecated()
    protected btSoftBodyRigidBodyCollisionConfiguration(byte b, char c) {
        super((byte) 1, (char) 1);
    }

    /**
     * @return An empty instance without a native address
     */
    public static btSoftBodyRigidBodyCollisionConfiguration native_new() {
        return new btSoftBodyRigidBodyCollisionConfiguration((byte) 0, (char) 0);
    }

    protected void deleteNative() {
        internal_native_deleteNative(native_address);
    }

    /*[-JNI;-NATIVE]
btSoftBodyRigidBodyCollisionConfiguration* nativeObject = (btSoftBodyRigidBodyCollisionConfiguration*)this_addr;
delete nativeObject;
*/
    public static native void internal_native_deleteNative(long this_addr);
}
