/*-------------------------------------------------------
 * This file was generated by JParser
 *
 * Do not make changes to this file
 *-------------------------------------------------------*/
package bullet.bulletcollision.collisiondispatch;

import com.github.xpenatan.jParser.idl.IDLBase;

public class btCollisionObjectWrapper extends IDLBase {

    static public final btCollisionObjectWrapper NULL = btCollisionObjectWrapper.native_new();

    /**
     * Dummy constructor, used internally to creates objects without C++ pointer
     */
    @Deprecated()
    protected btCollisionObjectWrapper(byte b, char c) {
    }

    /**
     * @return An empty instance without a native address
     */
    public static btCollisionObjectWrapper native_new() {
        return new btCollisionObjectWrapper((byte) 0, (char) 0);
    }
}
