/*-------------------------------------------------------
 * This file was generated by JParser
 *
 * Do not make changes to this file
 *-------------------------------------------------------*/
package bullet.bulletcollision.collisiondispatch;

import com.github.xpenatan.jParser.idl.IDLBase;

public class btCollisionConfiguration extends IDLBase {

    static public final btCollisionConfiguration NULL = btCollisionConfiguration.native_new();

    /**
     * Dummy constructor, used internally to creates objects without C++ pointer
     */
    @Deprecated()
    protected btCollisionConfiguration(byte b, char c) {
    }

    /**
     * @return An empty instance without a native address
     */
    public static btCollisionConfiguration native_new() {
        return new btCollisionConfiguration((byte) 0, (char) 0);
    }

    protected void deleteNative() {
        internal_native_deleteNative(native_address);
    }

    /*[-JNI;-NATIVE]
btCollisionConfiguration* nativeObject = (btCollisionConfiguration*)this_addr;
delete nativeObject;
*/
    public static native void internal_native_deleteNative(long this_addr);
}
