/*-------------------------------------------------------
 * This file was generated by JParser
 *
 * Do not make changes to this file
 *-------------------------------------------------------*/
package bullet.bulletcollision.collisiondispatch;

import bullet.bulletcollision.broadphasecollision.btDispatcher;

public class btCollisionDispatcher extends btDispatcher {

    static public final btCollisionDispatcher NULL = btCollisionDispatcher.native_new();

    public btCollisionDispatcher(btCollisionConfiguration conf) {
        super((byte) 1, (char) 1);
        long addr = internal_native_create_btCollisionConfiguration(conf.native_address);
        internal_reset(addr, true);
    }

    /*[-JNI;-NATIVE]
return (jlong)new btCollisionDispatcher((btCollisionConfiguration* )conf_addr);
*/
    public static native long internal_native_create_btCollisionConfiguration(long conf_addr);

    /**
     * Dummy constructor, used internally to creates objects without C++ pointer
     */
    @Deprecated()
    protected btCollisionDispatcher(byte b, char c) {
        super((byte) 1, (char) 1);
    }

    /**
     * @return An empty instance without a native address
     */
    public static btCollisionDispatcher native_new() {
        return new btCollisionDispatcher((byte) 0, (char) 0);
    }

    protected void deleteNative() {
        internal_native_deleteNative(native_address);
    }

    /*[-JNI;-NATIVE]
btCollisionDispatcher* nativeObject = (btCollisionDispatcher*)this_addr;
delete nativeObject;
*/
    public static native void internal_native_deleteNative(long this_addr);
}
