/*-------------------------------------------------------
 * This file was generated by JParser
 *
 * Do not make changes to this file
 *-------------------------------------------------------*/
package bullet.bulletcollision.collisiondispatch;

import bullet.btDefaultCollisionConstructionInfo;

public class btDefaultCollisionConfiguration extends btCollisionConfiguration {

    static public final btDefaultCollisionConfiguration NULL = btDefaultCollisionConfiguration.native_new();

    public btDefaultCollisionConfiguration(btDefaultCollisionConstructionInfo info) {
        super((byte) 1, (char) 1);
        long addr = internal_native_create_btDefaultCollisionConstructionInfo(info.native_address);
        internal_reset(addr, true);
    }

    /*[-JNI;-NATIVE]
return (jlong)new btDefaultCollisionConfiguration(*((btDefaultCollisionConstructionInfo* )info_addr));
*/
    public static native long internal_native_create_btDefaultCollisionConstructionInfo(long info_addr);

    public btDefaultCollisionConfiguration() {
        super((byte) 1, (char) 1);
        long addr = internal_native_create();
        internal_reset(addr, true);
    }

    /*[-JNI;-NATIVE]
return (jlong)new btDefaultCollisionConfiguration();
*/
    public static native long internal_native_create();

    /**
     * Dummy constructor, used internally to creates objects without C++ pointer
     */
    @Deprecated()
    protected btDefaultCollisionConfiguration(byte b, char c) {
        super((byte) 1, (char) 1);
    }

    /**
     * @return An empty instance without a native address
     */
    public static btDefaultCollisionConfiguration native_new() {
        return new btDefaultCollisionConfiguration((byte) 0, (char) 0);
    }

    protected void deleteNative() {
        internal_native_deleteNative(native_address);
    }

    /*[-JNI;-NATIVE]
btDefaultCollisionConfiguration* nativeObject = (btDefaultCollisionConfiguration*)this_addr;
delete nativeObject;
*/
    public static native void internal_native_deleteNative(long this_addr);
}
