/*-------------------------------------------------------
 * This file was generated by JParser
 *
 * Do not make changes to this file
 *-------------------------------------------------------*/
package bullet.bulletdynamics.constraintsolver;

import com.github.xpenatan.jParser.idl.IDLBase;

public class btConstraintSolver extends IDLBase {

    static public final btConstraintSolver NULL = btConstraintSolver.native_new();

    /**
     * Dummy constructor, used internally to creates objects without C++ pointer
     */
    @Deprecated()
    protected btConstraintSolver(byte b, char c) {
    }

    /**
     * @return An empty instance without a native address
     */
    public static btConstraintSolver native_new() {
        return new btConstraintSolver((byte) 0, (char) 0);
    }

    protected void deleteNative() {
        internal_native_deleteNative(native_address);
    }

    /*[-JNI;-NATIVE]
btConstraintSolver* nativeObject = (btConstraintSolver*)this_addr;
delete nativeObject;
*/
    public static native void internal_native_deleteNative(long this_addr);
}
