/*-------------------------------------------------------
 * This file was generated by JParser
 *
 * Do not make changes to this file
 *-------------------------------------------------------*/
package bullet.bulletdynamics.constraintsolver;

import com.github.xpenatan.jParser.idl.IDLBase;
import bullet.bulletdynamics.dynamics.btRigidBody;
import bullet.linearmath.btVector3;

public class btGearConstraint extends IDLBase {

    static public final btGearConstraint NULL = btGearConstraint.native_new();

    public btGearConstraint(btRigidBody rbA, btRigidBody rbB, btVector3 axisInA, btVector3 axisInB, float ratio) {
        long addr = internal_native_create_btRigidBody_btRigidBody_btVector3_btVector3_float(rbA.native_address, rbB.native_address, axisInA.native_address, axisInB.native_address, ratio);
        internal_reset(addr, true);
    }

    /*[-JNI;-NATIVE]
return (jlong)new btGearConstraint(*((btRigidBody* )rbA_addr), *((btRigidBody* )rbB_addr), *((btVector3* )axisInA_addr), *((btVector3* )axisInB_addr), (float)ratio);
*/
    public static native long internal_native_create_btRigidBody_btRigidBody_btVector3_btVector3_float(long rbA_addr, long rbB_addr, long axisInA_addr, long axisInB_addr, float ratio);

    public btGearConstraint(btRigidBody rbA, btRigidBody rbB, btVector3 axisInA, btVector3 axisInB) {
        long addr = internal_native_create_btRigidBody_btRigidBody_btVector3_btVector3(rbA.native_address, rbB.native_address, axisInA.native_address, axisInB.native_address);
        internal_reset(addr, true);
    }

    /*[-JNI;-NATIVE]
return (jlong)new btGearConstraint(*((btRigidBody* )rbA_addr), *((btRigidBody* )rbB_addr), *((btVector3* )axisInA_addr), *((btVector3* )axisInB_addr));
*/
    public static native long internal_native_create_btRigidBody_btRigidBody_btVector3_btVector3(long rbA_addr, long rbB_addr, long axisInA_addr, long axisInB_addr);

    /**
     * Dummy constructor, used internally to creates objects without C++ pointer
     */
    @Deprecated()
    protected btGearConstraint(byte b, char c) {
    }

    /**
     * @return An empty instance without a native address
     */
    public static btGearConstraint native_new() {
        return new btGearConstraint((byte) 0, (char) 0);
    }

    protected void deleteNative() {
        internal_native_deleteNative(native_address);
    }

    /*[-JNI;-NATIVE]
btGearConstraint* nativeObject = (btGearConstraint*)this_addr;
delete nativeObject;
*/
    public static native void internal_native_deleteNative(long this_addr);
}
