/*-------------------------------------------------------
 * This file was generated by JParser
 *
 * Do not make changes to this file
 *-------------------------------------------------------*/
package bullet.bulletdynamics.constraintsolver;

import bullet.bulletdynamics.dynamics.btRigidBody;
import bullet.linearmath.btTransform;

public class btGeneric6DofSpringConstraint extends btGeneric6DofConstraint {

    static public final btGeneric6DofSpringConstraint NULL = btGeneric6DofSpringConstraint.native_new();

    public btGeneric6DofSpringConstraint(btRigidBody rbA, btRigidBody rbB, btTransform frameInA, btTransform frameInB, boolean useLinearFrameReferenceFrameA) {
        super((byte) 1, (char) 1);
        long addr = internal_native_create_btRigidBody_btRigidBody_btTransform_btTransform_boolean(rbA.native_address, rbB.native_address, frameInA.native_address, frameInB.native_address, useLinearFrameReferenceFrameA);
        internal_reset(addr, true);
    }

    /*[-JNI;-NATIVE]
return (jlong)new btGeneric6DofSpringConstraint(*((btRigidBody* )rbA_addr), *((btRigidBody* )rbB_addr), *((btTransform* )frameInA_addr), *((btTransform* )frameInB_addr), useLinearFrameReferenceFrameA);
*/
    public static native long internal_native_create_btRigidBody_btRigidBody_btTransform_btTransform_boolean(long rbA_addr, long rbB_addr, long frameInA_addr, long frameInB_addr, boolean useLinearFrameReferenceFrameA);

    public btGeneric6DofSpringConstraint(btRigidBody rbB, btTransform frameInB, boolean useLinearFrameReferenceFrameB) {
        super((byte) 1, (char) 1);
        long addr = internal_native_create_btRigidBody_btTransform_boolean(rbB.native_address, frameInB.native_address, useLinearFrameReferenceFrameB);
        internal_reset(addr, true);
    }

    /*[-JNI;-NATIVE]
return (jlong)new btGeneric6DofSpringConstraint(*((btRigidBody* )rbB_addr), *((btTransform* )frameInB_addr), useLinearFrameReferenceFrameB);
*/
    public static native long internal_native_create_btRigidBody_btTransform_boolean(long rbB_addr, long frameInB_addr, boolean useLinearFrameReferenceFrameB);

    /**
     * Dummy constructor, used internally to creates objects without C++ pointer
     */
    @Deprecated()
    protected btGeneric6DofSpringConstraint(byte b, char c) {
        super((byte) 1, (char) 1);
    }

    /**
     * @return An empty instance without a native address
     */
    public static btGeneric6DofSpringConstraint native_new() {
        return new btGeneric6DofSpringConstraint((byte) 0, (char) 0);
    }

    protected void deleteNative() {
        internal_native_deleteNative(native_address);
    }

    /*[-JNI;-NATIVE]
btGeneric6DofSpringConstraint* nativeObject = (btGeneric6DofSpringConstraint*)this_addr;
delete nativeObject;
*/
    public static native void internal_native_deleteNative(long this_addr);

    public void enableSpring(int index, boolean onOff) {
        internal_native_enableSpring(native_address, index, onOff);
    }

    /*[-JNI;-NATIVE]
btGeneric6DofSpringConstraint* nativeObject = (btGeneric6DofSpringConstraint*)this_addr;
nativeObject->enableSpring((int)index, onOff);
*/
    public static native void internal_native_enableSpring(long this_addr, int index, boolean onOff);

    public void setStiffness(int index, float stiffness) {
        internal_native_setStiffness(native_address, index, stiffness);
    }

    /*[-JNI;-NATIVE]
btGeneric6DofSpringConstraint* nativeObject = (btGeneric6DofSpringConstraint*)this_addr;
nativeObject->setStiffness((int)index, (float)stiffness);
*/
    public static native void internal_native_setStiffness(long this_addr, int index, float stiffness);

    public void setDamping(int index, float damping) {
        internal_native_setDamping(native_address, index, damping);
    }

    /*[-JNI;-NATIVE]
btGeneric6DofSpringConstraint* nativeObject = (btGeneric6DofSpringConstraint*)this_addr;
nativeObject->setDamping((int)index, (float)damping);
*/
    public static native void internal_native_setDamping(long this_addr, int index, float damping);
}
