/*-------------------------------------------------------
 * This file was generated by JParser
 *
 * Do not make changes to this file
 *-------------------------------------------------------*/
package bullet.bulletdynamics.constraintsolver;

public class btSequentialImpulseConstraintSolver extends btConstraintSolver {

    static public final btSequentialImpulseConstraintSolver NULL = btSequentialImpulseConstraintSolver.native_new();

    public btSequentialImpulseConstraintSolver() {
        super((byte) 1, (char) 1);
        long addr = internal_native_create();
        internal_reset(addr, true);
    }

    /*[-JNI;-NATIVE]
return (jlong)new btSequentialImpulseConstraintSolver();
*/
    public static native long internal_native_create();

    /**
     * Dummy constructor, used internally to creates objects without C++ pointer
     */
    @Deprecated()
    protected btSequentialImpulseConstraintSolver(byte b, char c) {
        super((byte) 1, (char) 1);
    }

    /**
     * @return An empty instance without a native address
     */
    public static btSequentialImpulseConstraintSolver native_new() {
        return new btSequentialImpulseConstraintSolver((byte) 0, (char) 0);
    }

    protected void deleteNative() {
        internal_native_deleteNative(native_address);
    }

    /*[-JNI;-NATIVE]
btSequentialImpulseConstraintSolver* nativeObject = (btSequentialImpulseConstraintSolver*)this_addr;
delete nativeObject;
*/
    public static native void internal_native_deleteNative(long this_addr);
}
