/*-------------------------------------------------------
 * This file was generated by JParser
 *
 * Do not make changes to this file
 *-------------------------------------------------------*/
package bullet.bulletdynamics.dynamics;

import com.github.xpenatan.jParser.idl.IDLBase;
import bullet.bulletcollision.collisiondispatch.btCollisionWorld;
import bullet.linearmath.btIDebugDraw;

public class btActionInterface extends IDLBase {

    static public final btActionInterface NULL = btActionInterface.native_new();

    /**
     * Dummy constructor, used internally to creates objects without C++ pointer
     */
    @Deprecated()
    protected btActionInterface(byte b, char c) {
    }

    /**
     * @return An empty instance without a native address
     */
    public static btActionInterface native_new() {
        return new btActionInterface((byte) 0, (char) 0);
    }

    protected void deleteNative() {
        internal_native_deleteNative(native_address);
    }

    /*[-JNI;-NATIVE]
btActionInterface* nativeObject = (btActionInterface*)this_addr;
delete nativeObject;
*/
    public static native void internal_native_deleteNative(long this_addr);

    public void updateAction(btCollisionWorld collisionWorld, float deltaTimeStep) {
        internal_native_updateAction(native_address, collisionWorld.native_address, deltaTimeStep);
    }

    /*[-JNI;-NATIVE]
btActionInterface* nativeObject = (btActionInterface*)this_addr;
nativeObject->updateAction((btCollisionWorld* )collisionWorld_addr, (float)deltaTimeStep);
*/
    public static native void internal_native_updateAction(long this_addr, long collisionWorld_addr, float deltaTimeStep);

    public void debugDraw(btIDebugDraw debugDrawer) {
        internal_native_debugDraw(native_address, debugDrawer.native_address);
    }

    /*[-JNI;-NATIVE]
btActionInterface* nativeObject = (btActionInterface*)this_addr;
nativeObject->debugDraw((btIDebugDraw* )debugDrawer_addr);
*/
    public static native void internal_native_debugDraw(long this_addr, long debugDrawer_addr);
}
