/*-------------------------------------------------------
 * This file was generated by JParser
 *
 * Do not make changes to this file
 *-------------------------------------------------------*/
package bullet.bulletdynamics.dynamics;

import bullet.bulletcollision.broadphasecollision.btDispatcher;
import bullet.bulletcollision.broadphasecollision.btBroadphaseInterface;
import bullet.bulletdynamics.constraintsolver.btConstraintSolver;
import bullet.bulletcollision.collisiondispatch.btCollisionConfiguration;

public class btDiscreteDynamicsWorld extends btDynamicsWorld {

    static public final btDiscreteDynamicsWorld NULL = btDiscreteDynamicsWorld.native_new();

    public btDiscreteDynamicsWorld(btDispatcher dispatcher, btBroadphaseInterface pairCache, btConstraintSolver constraintSolver, btCollisionConfiguration collisionConfiguration) {
        super((byte) 1, (char) 1);
        long addr = internal_native_create_btDispatcher_btBroadphaseInterface_btConstraintSolver_btCollisionConfiguration(dispatcher.native_address, pairCache.native_address, constraintSolver.native_address, collisionConfiguration.native_address);
        internal_reset(addr, true);
    }

    /*[-JNI;-NATIVE]
return (jlong)new btDiscreteDynamicsWorld((btDispatcher* )dispatcher_addr, (btBroadphaseInterface* )pairCache_addr, (btConstraintSolver* )constraintSolver_addr, (btCollisionConfiguration* )collisionConfiguration_addr);
*/
    public static native long internal_native_create_btDispatcher_btBroadphaseInterface_btConstraintSolver_btCollisionConfiguration(long dispatcher_addr, long pairCache_addr, long constraintSolver_addr, long collisionConfiguration_addr);

    /**
     * Dummy constructor, used internally to creates objects without C++ pointer
     */
    @Deprecated()
    protected btDiscreteDynamicsWorld(byte b, char c) {
        super((byte) 1, (char) 1);
    }

    /**
     * @return An empty instance without a native address
     */
    public static btDiscreteDynamicsWorld native_new() {
        return new btDiscreteDynamicsWorld((byte) 0, (char) 0);
    }

    protected void deleteNative() {
        internal_native_deleteNative(native_address);
    }

    /*[-JNI;-NATIVE]
btDiscreteDynamicsWorld* nativeObject = (btDiscreteDynamicsWorld*)this_addr;
delete nativeObject;
*/
    public static native void internal_native_deleteNative(long this_addr);
}
