/*-------------------------------------------------------
 * This file was generated by JParser
 *
 * Do not make changes to this file
 *-------------------------------------------------------*/
package bullet.bulletcollision.collisionshapes;

import bullet.linearmath.btVector3;

public class btBoxShape extends btPolyhedralConvexShape {

    private btVector3 btVector3_TEMP_GEN_0;

    static public final btBoxShape NULL = btBoxShape.native_new();

    public btBoxShape(btVector3 boxHalfExtents) {
        super((byte) 1, (char) 1);
        long addr = internal_native_create_btVector3(boxHalfExtents.native_address);
        internal_reset(addr, true);
    }

    /*[-JNI;-NATIVE]
return (jlong)new btBoxShape(*((btVector3* )boxHalfExtents_addr));
*/
    public static native long internal_native_create_btVector3(long boxHalfExtents_addr);

    /**
     * Dummy constructor, used internally to creates objects without C++ pointer
     */
    @Deprecated()
    protected btBoxShape(byte b, char c) {
        super((byte) 1, (char) 1);
    }

    /**
     * @return An empty instance without a native address
     */
    public static btBoxShape native_new() {
        return new btBoxShape((byte) 0, (char) 0);
    }

    protected void deleteNative() {
        internal_native_deleteNative(native_address);
    }

    /*[-JNI;-NATIVE]
btBoxShape* nativeObject = (btBoxShape*)this_addr;
delete nativeObject;
*/
    public static native void internal_native_deleteNative(long this_addr);

    public void setMargin(float margin) {
        internal_native_setMargin(native_address, margin);
    }

    /*[-JNI;-NATIVE]
btBoxShape* nativeObject = (btBoxShape*)this_addr;
nativeObject->setMargin((float)margin);
*/
    public static native void internal_native_setMargin(long this_addr, float margin);

    public btVector3 getHalfExtentsWithoutMargin() {
        long pointer = internal_native_getHalfExtentsWithoutMargin(native_address);
        if (pointer == 0)
            return btVector3.NULL;
        if (btVector3_TEMP_GEN_0 == null)
            btVector3_TEMP_GEN_0 = btVector3.native_new();
        btVector3_TEMP_GEN_0.internal_reset(pointer, false);
        return btVector3_TEMP_GEN_0;
    }

    /*[-JNI;-NATIVE]
btBoxShape* nativeObject = (btBoxShape*)this_addr;
return (jlong)&nativeObject->getHalfExtentsWithoutMargin();
*/
    public static native long internal_native_getHalfExtentsWithoutMargin(long this_addr);

    public float getMargin() {
        return internal_native_getMargin(native_address);
    }

    /*[-JNI;-NATIVE]
btBoxShape* nativeObject = (btBoxShape*)this_addr;
return nativeObject->getMargin();
*/
    public static native float internal_native_getMargin(long this_addr);
}
