/*-------------------------------------------------------
 * This file was generated by JParser
 *
 * Do not make changes to this file
 *-------------------------------------------------------*/
package bullet.bulletcollision.collisionshapes;

import bullet.btPolyhedralConvexAabbCachingShape;

public class btConvexTriangleMeshShape extends btPolyhedralConvexAabbCachingShape {

    static public final btConvexTriangleMeshShape NULL = btConvexTriangleMeshShape.native_new();

    public btConvexTriangleMeshShape(btStridingMeshInterface meshInterface, boolean calcAabb) {
        super((byte) 1, (char) 1);
        long addr = internal_native_create_btStridingMeshInterface_boolean(meshInterface.native_address, calcAabb);
        internal_reset(addr, true);
    }

    /*[-JNI;-NATIVE]
return (jlong)new btConvexTriangleMeshShape((btStridingMeshInterface* )meshInterface_addr, calcAabb);
*/
    public static native long internal_native_create_btStridingMeshInterface_boolean(long meshInterface_addr, boolean calcAabb);

    public btConvexTriangleMeshShape(btStridingMeshInterface meshInterface) {
        super((byte) 1, (char) 1);
        long addr = internal_native_create_btStridingMeshInterface(meshInterface.native_address);
        internal_reset(addr, true);
    }

    /*[-JNI;-NATIVE]
return (jlong)new btConvexTriangleMeshShape((btStridingMeshInterface* )meshInterface_addr);
*/
    public static native long internal_native_create_btStridingMeshInterface(long meshInterface_addr);

    /**
     * Dummy constructor, used internally to creates objects without C++ pointer
     */
    @Deprecated()
    protected btConvexTriangleMeshShape(byte b, char c) {
        super((byte) 1, (char) 1);
    }

    /**
     * @return An empty instance without a native address
     */
    public static btConvexTriangleMeshShape native_new() {
        return new btConvexTriangleMeshShape((byte) 0, (char) 0);
    }

    protected void deleteNative() {
        internal_native_deleteNative(native_address);
    }

    /*[-JNI;-NATIVE]
btConvexTriangleMeshShape* nativeObject = (btConvexTriangleMeshShape*)this_addr;
delete nativeObject;
*/
    public static native void internal_native_deleteNative(long this_addr);
}
