/*-------------------------------------------------------
 * This file was generated by JParser
 *
 * Do not make changes to this file
 *-------------------------------------------------------*/
package bullet.bulletcollision.collisionshapes;

import bullet.linearmath.btVector3;

public class btConvexInternalShape extends btConvexShape {

    static public final btConvexInternalShape NULL = btConvexInternalShape.native_new();

    /**
     * Dummy constructor, used internally to creates objects without C++ pointer
     */
    @Deprecated()
    protected btConvexInternalShape(byte b, char c) {
        super((byte) 1, (char) 1);
    }

    /**
     * @return An empty instance without a native address
     */
    public static btConvexInternalShape native_new() {
        return new btConvexInternalShape((byte) 0, (char) 0);
    }

    protected void deleteNative() {
        internal_native_deleteNative(native_address);
    }

    /*[-JNI;-NATIVE]
btConvexInternalShape* nativeObject = (btConvexInternalShape*)this_addr;
delete nativeObject;
*/
    public static native void internal_native_deleteNative(long this_addr);

    public void setImplicitShapeDimensions(btVector3 dimensions) {
        internal_native_setImplicitShapeDimensions(native_address, dimensions.native_address);
    }

    /*[-JNI;-NATIVE]
btConvexInternalShape* nativeObject = (btConvexInternalShape*)this_addr;
nativeObject->setImplicitShapeDimensions(*((btVector3* )dimensions_addr));
*/
    public static native void internal_native_setImplicitShapeDimensions(long this_addr, long dimensions_addr);
}
