/*-------------------------------------------------------
 * This file was generated by JParser
 *
 * Do not make changes to this file
 *-------------------------------------------------------*/
package bullet.bulletcollision.collisionshapes;

import bullet.linearmath.btVector3;

public class btConvexShape extends btCollisionShape {

    static public final btConvexShape NULL = btConvexShape.native_new();

    /**
     * Dummy constructor, used internally to creates objects without C++ pointer
     */
    @Deprecated()
    protected btConvexShape(byte b, char c) {
        super((byte) 1, (char) 1);
    }

    /**
     * @return An empty instance without a native address
     */
    public static btConvexShape native_new() {
        return new btConvexShape((byte) 0, (char) 0);
    }

    protected void deleteNative() {
        internal_native_deleteNative(native_address);
    }

    /*[-JNI;-NATIVE]
btConvexShape* nativeObject = (btConvexShape*)this_addr;
delete nativeObject;
*/
    public static native void internal_native_deleteNative(long this_addr);

    public int getNumPreferredPenetrationDirections() {
        return internal_native_getNumPreferredPenetrationDirections(native_address);
    }

    /*[-JNI;-NATIVE]
btConvexShape* nativeObject = (btConvexShape*)this_addr;
return nativeObject->getNumPreferredPenetrationDirections();
*/
    public static native int internal_native_getNumPreferredPenetrationDirections(long this_addr);

    public void getPreferredPenetrationDirection(int index, btVector3 penetrationVector) {
        internal_native_getPreferredPenetrationDirection(native_address, index, penetrationVector.native_address);
    }

    /*[-JNI;-NATIVE]
btConvexShape* nativeObject = (btConvexShape*)this_addr;
nativeObject->getPreferredPenetrationDirection((int)index, *((btVector3* )penetrationVector_addr));
*/
    public static native void internal_native_getPreferredPenetrationDirection(long this_addr, int index, long penetrationVector_addr);
}
