/*-------------------------------------------------------
 * This file was generated by JParser
 *
 * Do not make changes to this file
 *-------------------------------------------------------*/
package bullet.bulletcollision.collisionshapes;

public class btConeShape extends btConvexInternalShape {

    static public final btConeShape NULL = btConeShape.native_new();

    public btConeShape(float radius, float height) {
        super((byte) 1, (char) 1);
        long addr = internal_native_create_float_float(radius, height);
        internal_reset(addr, true);
    }

    /*[-JNI;-NATIVE]
return (jlong)new btConeShape((float)radius, (float)height);
*/
    public static native long internal_native_create_float_float(float radius, float height);

    /**
     * Dummy constructor, used internally to creates objects without C++ pointer
     */
    @Deprecated()
    protected btConeShape(byte b, char c) {
        super((byte) 1, (char) 1);
    }

    /**
     * @return An empty instance without a native address
     */
    public static btConeShape native_new() {
        return new btConeShape((byte) 0, (char) 0);
    }

    protected void deleteNative() {
        internal_native_deleteNative(native_address);
    }

    /*[-JNI;-NATIVE]
btConeShape* nativeObject = (btConeShape*)this_addr;
delete nativeObject;
*/
    public static native void internal_native_deleteNative(long this_addr);
}
