/*-------------------------------------------------------
 * This file was generated by JParser
 *
 * Do not make changes to this file
 *-------------------------------------------------------*/
package bullet.bulletcollision.collisionshapes;

import bullet.linearmath.btTransform;

public class btCompoundShape extends btCollisionShape {

    private btCollisionShape btCollisionShape_TEMP_GEN_0;

    static public final btCompoundShape NULL = btCompoundShape.native_new();

    public btCompoundShape(boolean enableDynamicAabbTree) {
        super((byte) 1, (char) 1);
        long addr = internal_native_create_boolean(enableDynamicAabbTree);
        internal_reset(addr, true);
    }

    /*[-JNI;-NATIVE]
return (jlong)new btCompoundShape(enableDynamicAabbTree);
*/
    public static native long internal_native_create_boolean(boolean enableDynamicAabbTree);

    public btCompoundShape() {
        super((byte) 1, (char) 1);
        long addr = internal_native_create();
        internal_reset(addr, true);
    }

    /*[-JNI;-NATIVE]
return (jlong)new btCompoundShape();
*/
    public static native long internal_native_create();

    /**
     * Dummy constructor, used internally to creates objects without C++ pointer
     */
    @Deprecated()
    protected btCompoundShape(byte b, char c) {
        super((byte) 1, (char) 1);
    }

    /**
     * @return An empty instance without a native address
     */
    public static btCompoundShape native_new() {
        return new btCompoundShape((byte) 0, (char) 0);
    }

    protected void deleteNative() {
        internal_native_deleteNative(native_address);
    }

    /*[-JNI;-NATIVE]
btCompoundShape* nativeObject = (btCompoundShape*)this_addr;
delete nativeObject;
*/
    public static native void internal_native_deleteNative(long this_addr);

    public void addChildShape(btTransform localTransform, btCollisionShape shape) {
        internal_native_addChildShape(native_address, localTransform.native_address, shape.native_address);
    }

    /*[-JNI;-NATIVE]
btCompoundShape* nativeObject = (btCompoundShape*)this_addr;
nativeObject->addChildShape(*((btTransform* )localTransform_addr), (btCollisionShape* )shape_addr);
*/
    public static native void internal_native_addChildShape(long this_addr, long localTransform_addr, long shape_addr);

    public void removeChildShapeByIndex(int childShapeindex) {
        internal_native_removeChildShapeByIndex(native_address, childShapeindex);
    }

    /*[-JNI;-NATIVE]
btCompoundShape* nativeObject = (btCompoundShape*)this_addr;
nativeObject->removeChildShapeByIndex((int)childShapeindex);
*/
    public static native void internal_native_removeChildShapeByIndex(long this_addr, int childShapeindex);

    public void removeChildShape(btCollisionShape shape) {
        internal_native_removeChildShape(native_address, shape.native_address);
    }

    /*[-JNI;-NATIVE]
btCompoundShape* nativeObject = (btCompoundShape*)this_addr;
nativeObject->removeChildShape((btCollisionShape* )shape_addr);
*/
    public static native void internal_native_removeChildShape(long this_addr, long shape_addr);

    public int getNumChildShapes() {
        return internal_native_getNumChildShapes(native_address);
    }

    /*[-JNI;-NATIVE]
btCompoundShape* nativeObject = (btCompoundShape*)this_addr;
return nativeObject->getNumChildShapes();
*/
    public static native int internal_native_getNumChildShapes(long this_addr);

    public btCollisionShape getChildShape(int index) {
        long pointer = internal_native_getChildShape(native_address, index);
        if (pointer == 0)
            return btCollisionShape.NULL;
        if (btCollisionShape_TEMP_GEN_0 == null)
            btCollisionShape_TEMP_GEN_0 = btCollisionShape.native_new();
        btCollisionShape_TEMP_GEN_0.internal_reset(pointer, false);
        return btCollisionShape_TEMP_GEN_0;
    }

    /*[-JNI;-NATIVE]
btCompoundShape* nativeObject = (btCompoundShape*)this_addr;
btCollisionShape* obj = nativeObject->getChildShape((int)index);
return (jlong)obj;
*/
    public static native long internal_native_getChildShape(long this_addr, int index);

    public void setMargin(float margin) {
        internal_native_setMargin(native_address, margin);
    }

    /*[-JNI;-NATIVE]
btCompoundShape* nativeObject = (btCompoundShape*)this_addr;
nativeObject->setMargin((float)margin);
*/
    public static native void internal_native_setMargin(long this_addr, float margin);

    public float getMargin() {
        return internal_native_getMargin(native_address);
    }

    /*[-JNI;-NATIVE]
btCompoundShape* nativeObject = (btCompoundShape*)this_addr;
return nativeObject->getMargin();
*/
    public static native float internal_native_getMargin(long this_addr);

    public void recalculateLocalAabb() {
        internal_native_recalculateLocalAabb(native_address);
    }

    /*[-JNI;-NATIVE]
btCompoundShape* nativeObject = (btCompoundShape*)this_addr;
nativeObject->recalculateLocalAabb();
*/
    public static native void internal_native_recalculateLocalAabb(long this_addr);
}
