/*-------------------------------------------------------
 * This file was generated by JParser
 *
 * Do not make changes to this file
 *-------------------------------------------------------*/
package bullet.bulletcollision.collisionshapes;

import com.github.xpenatan.jParser.idl.IDLBase;
import bullet.linearmath.btVector3;

public class btScaledBvhTriangleMeshShape extends IDLBase {

    static public final btScaledBvhTriangleMeshShape NULL = btScaledBvhTriangleMeshShape.native_new();

    public btScaledBvhTriangleMeshShape(btBvhTriangleMeshShape childShape, btVector3 localScaling) {
        long addr = internal_native_create_btBvhTriangleMeshShape_btVector3(childShape.native_address, localScaling.native_address);
        internal_reset(addr, true);
    }

    /*[-JNI;-NATIVE]
return (jlong)new btScaledBvhTriangleMeshShape((btBvhTriangleMeshShape* )childShape_addr, *((btVector3* )localScaling_addr));
*/
    public static native long internal_native_create_btBvhTriangleMeshShape_btVector3(long childShape_addr, long localScaling_addr);

    /**
     * Dummy constructor, used internally to creates objects without C++ pointer
     */
    @Deprecated()
    protected btScaledBvhTriangleMeshShape(byte b, char c) {
    }

    /**
     * @return An empty instance without a native address
     */
    public static btScaledBvhTriangleMeshShape native_new() {
        return new btScaledBvhTriangleMeshShape((byte) 0, (char) 0);
    }

    protected void deleteNative() {
        internal_native_deleteNative(native_address);
    }

    /*[-JNI;-NATIVE]
btScaledBvhTriangleMeshShape* nativeObject = (btScaledBvhTriangleMeshShape*)this_addr;
delete nativeObject;
*/
    public static native void internal_native_deleteNative(long this_addr);
}
