/*-------------------------------------------------------
 * This file was generated by JParser
 *
 * Do not make changes to this file
 *-------------------------------------------------------*/
package bullet.bulletcollision.collisionshapes;

import com.github.xpenatan.jParser.idl.IDLBase;

public class btShapeHull extends IDLBase {

    static public final btShapeHull NULL = btShapeHull.native_new();

    public btShapeHull(btConvexShape shape) {
        long addr = internal_native_create_btConvexShape(shape.native_address);
        internal_reset(addr, true);
    }

    /*[-JNI;-NATIVE]
return (jlong)new btShapeHull((btConvexShape* )shape_addr);
*/
    public static native long internal_native_create_btConvexShape(long shape_addr);

    /**
     * Dummy constructor, used internally to creates objects without C++ pointer
     */
    @Deprecated()
    protected btShapeHull(byte b, char c) {
    }

    /**
     * @return An empty instance without a native address
     */
    public static btShapeHull native_new() {
        return new btShapeHull((byte) 0, (char) 0);
    }

    protected void deleteNative() {
        internal_native_deleteNative(native_address);
    }

    /*[-JNI;-NATIVE]
btShapeHull* nativeObject = (btShapeHull*)this_addr;
delete nativeObject;
*/
    public static native void internal_native_deleteNative(long this_addr);

    public int numTriangles() {
        return internal_native_numTriangles(native_address);
    }

    /*[-JNI;-NATIVE]
btShapeHull* nativeObject = (btShapeHull*)this_addr;
return nativeObject->numTriangles();
*/
    public static native int internal_native_numTriangles(long this_addr);

    public int numVertices() {
        return internal_native_numVertices(native_address);
    }

    /*[-JNI;-NATIVE]
btShapeHull* nativeObject = (btShapeHull*)this_addr;
return nativeObject->numVertices();
*/
    public static native int internal_native_numVertices(long this_addr);

    public int numIndices() {
        return internal_native_numIndices(native_address);
    }

    /*[-JNI;-NATIVE]
btShapeHull* nativeObject = (btShapeHull*)this_addr;
return nativeObject->numIndices();
*/
    public static native int internal_native_numIndices(long this_addr);

    public boolean buildHull(float margin) {
        return internal_native_buildHull(native_address, margin);
    }

    /*[-JNI;-NATIVE]
btShapeHull* nativeObject = (btShapeHull*)this_addr;
return nativeObject->buildHull((float)margin);
*/
    public static native boolean internal_native_buildHull(long this_addr, float margin);
}
