/*-------------------------------------------------------
 * This file was generated by JParser
 *
 * Do not make changes to this file
 *-------------------------------------------------------*/
package bullet.bulletcollision.collisionshapes;

public class btSphereShape extends btConvexInternalShape {

    static public final btSphereShape NULL = btSphereShape.native_new();

    public btSphereShape(float radius) {
        super((byte) 1, (char) 1);
        long addr = internal_native_create_float(radius);
        internal_reset(addr, true);
    }

    /*[-JNI;-NATIVE]
return (jlong)new btSphereShape((float)radius);
*/
    public static native long internal_native_create_float(float radius);

    /**
     * Dummy constructor, used internally to creates objects without C++ pointer
     */
    @Deprecated()
    protected btSphereShape(byte b, char c) {
        super((byte) 1, (char) 1);
    }

    /**
     * @return An empty instance without a native address
     */
    public static btSphereShape native_new() {
        return new btSphereShape((byte) 0, (char) 0);
    }

    protected void deleteNative() {
        internal_native_deleteNative(native_address);
    }

    /*[-JNI;-NATIVE]
btSphereShape* nativeObject = (btSphereShape*)this_addr;
delete nativeObject;
*/
    public static native void internal_native_deleteNative(long this_addr);

    public float getRadius() {
        return internal_native_getRadius(native_address);
    }

    /*[-JNI;-NATIVE]
btSphereShape* nativeObject = (btSphereShape*)this_addr;
return nativeObject->getRadius();
*/
    public static native float internal_native_getRadius(long this_addr);

    public void setUnscaledRadius(float radius) {
        internal_native_setUnscaledRadius(native_address, radius);
    }

    /*[-JNI;-NATIVE]
btSphereShape* nativeObject = (btSphereShape*)this_addr;
nativeObject->setUnscaledRadius((float)radius);
*/
    public static native void internal_native_setUnscaledRadius(long this_addr, float radius);

    public void setMargin(float margin) {
        internal_native_setMargin(native_address, margin);
    }

    /*[-JNI;-NATIVE]
btSphereShape* nativeObject = (btSphereShape*)this_addr;
nativeObject->setMargin((float)margin);
*/
    public static native void internal_native_setMargin(long this_addr, float margin);

    public float getMargin() {
        return internal_native_getMargin(native_address);
    }

    /*[-JNI;-NATIVE]
btSphereShape* nativeObject = (btSphereShape*)this_addr;
return nativeObject->getMargin();
*/
    public static native float internal_native_getMargin(long this_addr);
}
