/*-------------------------------------------------------
 * This file was generated by JParser
 *
 * Do not make changes to this file
 *-------------------------------------------------------*/
package bullet.bulletcollision.collisionshapes;

import com.github.xpenatan.jParser.idl.IDLBase;

public class btStridingMeshInterface extends IDLBase {

    static public final btStridingMeshInterface NULL = btStridingMeshInterface.native_new();

    /**
     * Dummy constructor, used internally to creates objects without C++ pointer
     */
    @Deprecated()
    protected btStridingMeshInterface(byte b, char c) {
    }

    /**
     * @return An empty instance without a native address
     */
    public static btStridingMeshInterface native_new() {
        return new btStridingMeshInterface((byte) 0, (char) 0);
    }

    protected void deleteNative() {
        internal_native_deleteNative(native_address);
    }

    /*[-JNI;-NATIVE]
btStridingMeshInterface* nativeObject = (btStridingMeshInterface*)this_addr;
delete nativeObject;
*/
    public static native void internal_native_deleteNative(long this_addr);
}
