/*-------------------------------------------------------
 * This file was generated by JParser
 *
 * Do not make changes to this file
 *-------------------------------------------------------*/
package bullet.bulletcollision.collisionshapes;

import bullet.linearmath.btVector3;

public class btTriangleIndexVertexArray extends btStridingMeshInterface {

    static public final btTriangleIndexVertexArray NULL = btTriangleIndexVertexArray.native_new();

    public btTriangleIndexVertexArray() {
        super((byte) 1, (char) 1);
        long addr = internal_native_create();
        internal_reset(addr, true);
    }

    /*[-JNI;-NATIVE]
return (jlong)new btTriangleIndexVertexArray();
*/
    public static native long internal_native_create();

    /**
     * Dummy constructor, used internally to creates objects without C++ pointer
     */
    @Deprecated()
    protected btTriangleIndexVertexArray(byte b, char c) {
        super((byte) 1, (char) 1);
    }

    /**
     * @return An empty instance without a native address
     */
    public static btTriangleIndexVertexArray native_new() {
        return new btTriangleIndexVertexArray((byte) 0, (char) 0);
    }

    protected void deleteNative() {
        internal_native_deleteNative(native_address);
    }

    /*[-JNI;-NATIVE]
btTriangleIndexVertexArray* nativeObject = (btTriangleIndexVertexArray*)this_addr;
delete nativeObject;
*/
    public static native void internal_native_deleteNative(long this_addr);

    public void setPremadeAabb(btVector3 aabbMin, btVector3 aabbMax) {
        internal_native_setPremadeAabb(native_address, aabbMin.native_address, aabbMax.native_address);
    }

    /*[-JNI;-NATIVE]
btTriangleIndexVertexArray* nativeObject = (btTriangleIndexVertexArray*)this_addr;
nativeObject->setPremadeAabb(*((btVector3* )aabbMin_addr), *((btVector3* )aabbMax_addr));
*/
    public static native void internal_native_setPremadeAabb(long this_addr, long aabbMin_addr, long aabbMax_addr);

    public void getPremadeAabb(btVector3 aabbMin, btVector3 aabbMax) {
        internal_native_getPremadeAabb(native_address, aabbMin.native_address, aabbMax.native_address);
    }

    /*[-JNI;-NATIVE]
btTriangleIndexVertexArray* nativeObject = (btTriangleIndexVertexArray*)this_addr;
nativeObject->getPremadeAabb((btVector3* )aabbMin_addr, (btVector3* )aabbMax_addr);
*/
    public static native void internal_native_getPremadeAabb(long this_addr, long aabbMin_addr, long aabbMax_addr);

    public boolean hasPremadeAabb() {
        return internal_native_hasPremadeAabb(native_address);
    }

    /*[-JNI;-NATIVE]
btTriangleIndexVertexArray* nativeObject = (btTriangleIndexVertexArray*)this_addr;
return nativeObject->hasPremadeAabb();
*/
    public static native boolean internal_native_hasPremadeAabb(long this_addr);
}
