name: Build and Upload

on:
  workflow_call:
    inputs:
      isRelease:
        required: true
        type: boolean
      shouldUpload:
        required: true
        type: boolean

env:
  CENTRAL_PORTAL_USERNAME: ${{ secrets.CENTRAL_PORTAL_USERNAME }}
  CENTRAL_PORTAL_PASSWORD: ${{ secrets.CENTRAL_PORTAL_PASSWORD }}
  SIGNING_KEY: ${{ secrets.PGP_SECRET }}
  SIGNING_PASSWORD: ${{ secrets.PGP_PASSPHRASE }}

jobs:
  build_windows:
    name: Build Windows
    runs-on: windows-latest
    
    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.12.1
        with:
          access_token: ${{ github.token }}

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: "corretto"
          java-version: 17

      - name: Set up MinGW
        uses: msys2/setup-msys2@v2

      - name: Set up Developer Command Prompt
        uses: TheMrMilchmann/setup-msvc-dev@v3
        with:
          arch: x64

      - name: Append the directory of 'vcvarsall.bat' to PATH environment variable
        uses: myci-actions/export-env-var-powershell@1
        with:
          name: PATH
          value: $env:PATH;C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Auxiliary\Build

      - name: Download sources
        run: ./gradlew :bullet:bullet-build:bullet_download_source

      - name: Build project
        run: ./gradlew :bullet:bullet-build:bullet_build_project_windows64

      - name: Upload natives
        uses: actions/upload-artifact@v4
        with:
          name: windows-natives
          path: ./bullet/bullet-build/build/c++/libs/

  build_teavm:
    name: Build TeaVM
    runs-on: ubuntu-latest

    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.12.1
        with:
          access_token: ${{ github.token }}

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: "zulu"
          java-version: 17

      - name: Set up MinGW
        run: |
          sudo apt install -y --force-yes mingw-w64 lib32z1

      - name: Install emscripten
        uses: mymindstorm/setup-emsdk@v14
        with:
          version: 4.0.4

      - name: Change wrapper permissions
        run: chmod +x ./gradlew

      - name: Download sources
        run: ./gradlew :bullet:bullet-build:bullet_download_source

      - name: Build project
        run: ./gradlew :bullet:bullet-build:bullet_build_project_teavm

      - name: Upload natives
        uses: actions/upload-artifact@v4
        with:
          name: teavm-natives
          path: ./bullet/bullet-build/build/c++/libs/

  build_android:
    name: Build Android
    runs-on: ubuntu-latest

    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.12.1
        with:
          access_token: ${{ github.token }}

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: "corretto"
          java-version: 17

      - name: Set up MinGW
        run: |
          sudo apt install -y --force-yes mingw-w64 lib32z1

      - name: Install NDK
        id: setup-ndk
        uses: nttld/setup-ndk@v1
        with:
          ndk-version: r27d
          add-to-path: false

      - name: Change wrapper permissions
        run: chmod +x ./gradlew

      - name: Download sources
        run: ./gradlew :bullet:bullet-build:bullet_download_source

      - name: Build project
        run: ./gradlew :bullet:bullet-build:bullet_build_project_android
        env:
          NDK_HOME: ${{ steps.setup-ndk.outputs.ndk-path }}

      - name: Upload natives
        uses: actions/upload-artifact@v4
        with:
          name: android-natives
          path: ./bullet/bullet-build/build/c++/libs/

  upload_natives:
    name: Upload Natives
    needs: [build_windows, build_teavm, build_android]
    runs-on: ubuntu-latest

    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.12.1
        with:
          access_token: ${{ github.token }}

      - name: Checkout repository with latest changes
        uses: actions/checkout@v4
        with:
          ref: ${{ github.ref }}
          fetch-depth: 0

      - name: Pull latest changes
        run: |
          git pull origin ${{ github.ref_name }}  # Pulls the latest from the branch

      - name: Get version
        uses: madhead/read-java-properties@latest
        id: version
        with:
          file: "./gradle.properties"
          property: version
          default: 0.0.1

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: "corretto"
          java-version: 17

      - name: Set up MinGW
        run: |
          sudo apt install -y --force-yes mingw-w64 lib32z1

      - name: Change wrapper permissions
        run: chmod +x ./gradlew

      - name: Download windows natives
        uses: actions/download-artifact@v4
        with:
          name: windows-natives
          path: ./bullet/bullet-build/build/c++/libs/

#      - name: Download linux natives
#        uses: actions/download-artifact@v4
#        with:
#          name: linux-natives
#          path: ./bullet/bullet-build/build/c++/libs/
#
#      - name: Download mac natives
#        uses: actions/download-artifact@v4
#        with:
#          name: mac-natives
#          path: ./bullet/bullet-build/build/c++/libs/
#
      - name: Download android natives
        uses: actions/download-artifact@v4
        with:
          name: android-natives
          path: ./bullet/bullet-build/build/c++/libs/

      - name: Download teavm natives
        uses: actions/download-artifact@v4
        with:
          name: teavm-natives
          path: ./bullet/bullet-build/build/c++/libs/

      - name: Download sources
        run: ./gradlew :bullet:bullet-build:bullet_download_source

      - name: Build project
        run: ./gradlew :bullet:bullet-build:bullet_build_project

      - name: Upload Release to repository
        uses: nick-fields/retry@v3
        if: ${{ inputs.shouldUpload && inputs.isRelease }}
        with:
          max_attempts: 3
          timeout_minutes: 10
          retry_on: error
          command: ./gradlew publishRelease

      - name: Upload Snapshot to repository
        uses: nick-fields/retry@v3
        if: ${{ inputs.shouldUpload && !inputs.isRelease }}
        with:
          max_attempts: 3
          timeout_minutes: 10
          retry_on: error
          command: ./gradlew publishSnapshot

      - name: Create Git tag
        uses: actions/github-script@v7
        if: ${{ inputs.isRelease }}
        with:
          script: |
            const versionOutputs = ${{ toJSON(steps.version.outputs) }};

            var version = versionOutputs.value;

            console.log("Version: " + version);

            var ref = "refs/tags/" + version
            github.rest.git.createRef({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: ref,
              sha: context.sha
            });